<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Hardware.Info</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.Diagnostics.PerformanceCounter">
      <HintPath>..\..\System.Diagnostics.PerformanceCounter.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Win32.Registry">
      <HintPath>..\..\Microsoft.Win32.Registry.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>