namespace Xbim.Ifc4x3.ElectricalDomain;

public enum IfcCommunicationsApplianceTypeEnum : byte
{
	ANTENNA,
	AUTOMATON,
	COMPUTER,
	FAX,
	GATEWAY,
	INTELLIGENTPERIPHERAL,
	IPNETWORKEQUIPMENT,
	LINESIDEELECTRONICUNIT,
	MODEM,
	NETWORKAPPLIANCE,
	NETWORKBRIDGE,
	NETWORKHUB,
	OPTICALLINETERMINAL,
	OPTICALNETWORKUNIT,
	PRINTER,
	RADIOBLOCKCENTER,
	REPEATER,
	ROUTER,
	SCANNER,
	TELECOMMAND,
	TELEPHONYEXCHANGE,
	TRANSITIONCOMPONENT,
	TRANSPONDER,
	TRANSPORTEQUIPMENT,
	USERDEFINED,
	NOTDEFINED
}
