namespace Xbim.Ifc4x3.ElectricalDomain;

public enum IfcSwitchingDeviceTypeEnum : byte
{
	CONTACTOR,
	DIMMERSWITCH,
	EMERGENCYSTOP,
	KEYPAD,
	MOMENTARYSWITCH,
	RELAY,
	SELECTORSWITCH,
	STARTER,
	START_AND_STOP_EQUIPMENT,
	SWITCHDISCONNECTOR,
	TOGGLESWITCH,
	USERDEFINED,
	NOTDEFINED
}
