<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>buPowerNest</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="-83af42fd-9d96-4a96-ab01-e96d3dd2da63-" />
    <EmbeddedResource Include="-83af42fd-9d96-4a96-ab01-e96d3dd2da63-" LogicalName="{83af42fd-9d96-4a96-ab01-e96d3dd2da63}" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>