<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>protobuf-net</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net452</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Xml" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>