namespace Xbim.Ifc2x3.PlumbingFireProtectionDomain;

public enum IfcWasteTerminalTypeEnum : byte
{
	FLOORTRAP,
	FLOORWASTE,
	GULLYSUMP,
	GULLYTRAP,
	GREASEINTERCEPTOR,
	OILINTERCEPTOR,
	PETROLINTERCEPTOR,
	ROOFDRAIN,
	WASTEDISPOSALUNIT,
	WASTETRAP,
	USERDEFINED,
	NOTDEFINED
}
