namespace Xbim.Ifc2x3.ElectricalDomain;

public enum IfcElectricDistributionPointFunctionEnum : byte
{
	ALARMPANEL,
	CONSUMERUNIT,
	CONTROLPANEL,
	DISTRIBUTIONBOARD,
	GASDETECTORPANEL,
	INDICATORPANEL,
	MIMICPANEL,
	MOTORCONTROLCENTRE,
	SWITCHBOARD,
	USERDEFINED,
	NOTDEFINED
}
