namespace Xbim.Ifc2x3.ElectricalDomain;

public enum IfcElectricApplianceTypeEnum : byte
{
	COMPUTER,
	DIRECTWATERHEATER,
	DISHWASHER,
	ELECTRICCOOKER,
	ELECTRICHEATER,
	FACSIMILE,
	FREESTANDINGFAN,
	FREEZER,
	FRIDGE_FREEZER,
	HANDDRYER,
	INDIRECTWATERHEATER,
	MICROWAVE,
	PHOTOCOPIER,
	PRINTER,
	REFRIGERATOR,
	RADIANTHEATER,
	SCANNER,
	TELEPHONE,
	TUMBLEDRYER,
	TV,
	VENDINGMACHINE,
	WASHINGMACHINE,
	WATERHEATER,
	WATERCOOLER,
	USERDEFINED,
	NOTDEFINED
}
