// Decompiled with JetBrains decompiler
// Type: SmartAssembly.HouseOfCards.MemberRefsProxy
// Assembly: buEyeBase, Version=5.1.1.1, Culture=neutral, PublicKeyToken=null
// MVID: B5B7A040-6595-420F-97D2-D0DA226BD1F1
// Assembly location: C:\Users\ERCAN\Downloads\de4dot-net48\testTemiz\buEyeBase.dll

using buControls.Components;
using buControls.Controls;
using buEyeBaseVer5.Apps.Marble;
using buEyeBaseVer5.ClassViewer;
using buEyeBaseVer5.Forms.Cam;
using buEyeBaseVer5.Forms.Controls;
using buEyeBaseVer5.Forms.Profile;
using buEyeBaseVer5.Forms.Sewing;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows.Forms;

#nullable disable
namespace SmartAssembly.HouseOfCards;

public static class MemberRefsProxy
{
  public const MarbleMachineType DualHeadMilling5AxisSaw5Axis = ; // Unable to render the field
  [SpecialName]
  public int value__;

  static void \u0001([In] F_SewingFootHeight obj0)
  {
    ((F_Settnigs) obj0).FootHeight = (double) ((F_Settnigs) obj0).\u0001.Value;
  }

  static void \u0001([In] F_ControlUIButton obj0)
  {
    ((F_CamTriMeshSettings) obj0).\u0001 = (IContainer) new Container();
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (F_ControlUIButton));
    ((F_CamTriMeshSettings) obj0).IC32 = new ImageList(((F_CamTriMeshSettings) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).buGround1 = new buGround();
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone = new buSpin();
    ((F_CamTriMeshSettings) obj0).btn_displaytodown = new buButton();
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone = new buSpin();
    ((F_CamTriMeshSettings) obj0).btn_displaytoover = new buButton();
    ((F_CamTriMeshSettings) obj0).spn_geometryrad = new buSpin();
    ((F_CamTriMeshSettings) obj0).\u0002 = new buComboBox();
    ((F_CamTriMeshSettings) obj0).\u0001 = new buComboBox();
    ((F_CamTriMeshSettings) obj0).\u0002 = new buControlDisplaySet();
    ((F_CamTriMeshSettings) obj0).\u0003 = new buControlDisplaySet();
    ((F_CamTriMeshSettings) obj0).btn_ref = new buButton();
    ((F_CamTriMeshSettings) obj0).\u0001 = new buControlDisplaySet();
    ((F_CamTriMeshSettings) obj0).btn_ok = new buButton();
    ((F_CamTriMeshSettings) obj0).btn_cancel = new buButton();
    ((F_CamTriMeshSettings) obj0).btn_close = new buButton();
    ((F_CamTriMeshSettings) obj0).buGround1.SuspendLayout();
    obj0.SuspendLayout();
    ((F_CamTriMeshSettings) obj0).IC32.ImageStream = (ImageListStreamer) componentResourceManager.GetObject("IC32.ImageStream");
    ((F_CamTriMeshSettings) obj0).IC32.TransparentColor = Color.Transparent;
    ((F_CamTriMeshSettings) obj0).IC32.Images.SetKeyName(0, "warning2.ico");
    ((F_CamTriMeshSettings) obj0).IC32.Images.SetKeyName(1, "Error2.ico");
    ((F_CamTriMeshSettings) obj0).IC32.Images.SetKeyName(2, "Information2.ico");
    ((F_CamTriMeshSettings) obj0).buGround1.AuxInfo = (string) null;
    ((F_CamTriMeshSettings) obj0).buGround1.BackColor = Color.Transparent;
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).spn_displaytodowntone);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).btn_displaytodown);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).spn_displaytoovertone);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).btn_displaytoover);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).spn_geometryrad);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).\u0002);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).\u0002);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).\u0003);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).btn_ref);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).btn_ok);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).btn_cancel);
    ((F_CamTriMeshSettings) obj0).buGround1.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).btn_close);
    ((F_CamTriMeshSettings) obj0).buGround1.Display.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).buGround1.Display.Fonts.Font = new Font("Microsoft Sans Serif", 13.8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).buGround1.Display.GradientType = GradientMode.Lineer;
    ((F_CamTriMeshSettings) obj0).buGround1.Display.LineerGradient.FirstColor = Color.Black;
    ((F_CamTriMeshSettings) obj0).buGround1.Display.LineerGradient.SecondColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).buGround1.DisplayBottom.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).buGround1.DisplayTop.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).buGround1.DisplayTop.Fonts.Font = new Font("Tahoma", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).buGround1.Dock = DockStyle.Fill;
    ((F_CamTriMeshSettings) obj0).buGround1.Font = new Font("Microsoft Sans Serif", 13.8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).buGround1.Ground.TopHeight = 50;
    ((F_CamTriMeshSettings) obj0).buGround1.Image = (Image) null;
    ((F_CamTriMeshSettings) obj0).buGround1.ImageAlign = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).buGround1.Location = new Point(0, 0);
    ((F_CamTriMeshSettings) obj0).buGround1.Name = "buGround1";
    ((F_CamTriMeshSettings) obj0).buGround1.Sizable = true;
    ((F_CamTriMeshSettings) obj0).buGround1.Size = new Size(1396, 480);
    ((F_CamTriMeshSettings) obj0).buGround1.SmartBounds = true;
    ((F_CamTriMeshSettings) obj0).buGround1.StartPosition = FormStartPosition.Manual;
    ((F_CamTriMeshSettings) obj0).buGround1.TabIndex = 59;
    ((F_CamTriMeshSettings) obj0).buGround1.Text = "Button Settings";
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Aux.AuxInfo = "Spin2";
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.ButtonNormalDisplay.BackColor = Color.LightSteelBlue;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Caption.Caption = "Font Angle";
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Caption.Display.BackColor = Color.Silver;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Caption.Display.Fonts.Alignment = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Caption.Display.Fonts.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Caption.HeightPersentage = 50.0;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Caption.Width = 140;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.CheckTick.TickDisplay.BackColor = Color.WhiteSmoke;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.CheckTick.Visible = false;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.DecimalPoint = 1;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Display.BackColor = Color.WhiteSmoke;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Geometry.ArcDiameter = 6;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Image = (Image) null;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.IncrementStep = 1.0;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Location = new Point(142, 297);
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Name = "spn_displaytodowntone";
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Size = new Size(146, 34);
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.TabIndex = 872;
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Text = "Length";
    ((F_CamTriMeshSettings) obj0).spn_displaytodowntone.Value = 0.8;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.ButtonCopy = false;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Display.BackColor = Color.DarkGray;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Display.Fonts.Alignment = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Display.Fonts.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Geometry.ArcDiameter = 6;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Image = (Image) null;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.ImageAlign = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Location = new Point(3, 297);
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Name = "btn_displaytodown";
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Size = new Size(138, 35);
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.TabIndex = 871;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Text = "Display >> Down";
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.UseMnemonic = false;
    ((F_CamTriMeshSettings) obj0).btn_displaytodown.Click += new EventHandler(((buClassViewerColor5) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Aux.AuxInfo = "Spin2";
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.ButtonNormalDisplay.BackColor = Color.LightSteelBlue;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Caption.Caption = "Font Angle";
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Caption.Display.BackColor = Color.Silver;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Caption.Display.Fonts.Alignment = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Caption.Display.Fonts.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Caption.HeightPersentage = 50.0;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Caption.Width = 140;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.CheckTick.TickDisplay.BackColor = Color.WhiteSmoke;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.CheckTick.Visible = false;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.DecimalPoint = 1;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Display.BackColor = Color.WhiteSmoke;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Geometry.ArcDiameter = 6;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Image = (Image) null;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.IncrementStep = 1.0;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Location = new Point(142, 253);
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Name = "spn_displaytoovertone";
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Size = new Size(146, 34);
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.TabIndex = 870;
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Text = "Length";
    ((F_CamTriMeshSettings) obj0).spn_displaytoovertone.Value = 0.9;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.ButtonCopy = false;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Display.BackColor = Color.DarkGray;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Display.Fonts.Alignment = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Display.Fonts.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Geometry.ArcDiameter = 6;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Image = (Image) null;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.ImageAlign = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Location = new Point(3, 253);
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Name = "btn_displaytoover";
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Size = new Size(138, 35);
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.TabIndex = 869;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Text = "Display  >>  Over";
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.UseMnemonic = false;
    ((F_CamTriMeshSettings) obj0).btn_displaytoover.Click += new EventHandler(((buClassViewerColor5) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Aux.AuxInfo = "Spin2";
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.ButtonNormalDisplay.BackColor = Color.LightSteelBlue;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Caption.Caption = "Geometry Radius";
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Caption.Display.BackColor = Color.Silver;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Caption.Display.Fonts.Alignment = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Caption.Display.Fonts.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Caption.HeightPersentage = 50.0;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Caption.Visible = true;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Caption.Width = 140;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.CheckTick.TickDisplay.BackColor = Color.WhiteSmoke;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.CheckTick.Visible = false;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.DecimalPoint = 0;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Display.BackColor = Color.WhiteSmoke;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Geometry.ArcDiameter = 6;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Image = (Image) null;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.IncrementStep = 1.0;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Location = new Point(3, 212);
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Name = "spn_geometryrad";
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Size = new Size(285, 34);
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.TabIndex = 867;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Text = "Length";
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.Value = 0.0;
    ((F_CamTriMeshSettings) obj0).spn_geometryrad.ValueChanged += new buControlEvents.buValueChangedEvent(((buClassViewerColor5) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).\u0002.AuxInfo = (string) null;
    ((F_CamTriMeshSettings) obj0).\u0002.BackColor = Color.Transparent;
    ((F_CamTriMeshSettings) obj0).\u0002.Caption.Caption = "Geometry";
    ((F_CamTriMeshSettings) obj0).\u0002.Caption.Display.BackColor = Color.Silver;
    ((F_CamTriMeshSettings) obj0).\u0002.Caption.Display.Fonts.Alignment = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).\u0002.Caption.Display.Fonts.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).\u0002.Caption.HeightPersentage = 50.0;
    ((F_CamTriMeshSettings) obj0).\u0002.Caption.Visible = true;
    ((F_CamTriMeshSettings) obj0).\u0002.Caption.Width = 140;
    ((F_CamTriMeshSettings) obj0).\u0002.Display.Fonts.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).\u0002.Display.SelectionColor = Color.LightSteelBlue;
    ((F_CamTriMeshSettings) obj0).\u0002.DrawMode = DrawMode.OwnerDrawFixed;
    ((F_CamTriMeshSettings) obj0).\u0002.DropDownStyle = ComboBoxStyle.DropDownList;
    ((F_CamTriMeshSettings) obj0).\u0002.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).\u0002.FormattingEnabled = true;
    ((F_CamTriMeshSettings) obj0).\u0002.Geometry.ArcDiameter = 6;
    ((F_CamTriMeshSettings) obj0).\u0002.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).\u0002.ItemHeight = 25;
    ((F_CamTriMeshSettings) obj0).\u0002.Items.AddRange(new object[4]
    {
      (object) "Solid",
      (object) "Linear Gradient",
      (object) "Center Path Gradient",
      (object) "Interpolated Path Gradient"
    });
    ((F_CamTriMeshSettings) obj0).\u0002.Location = new Point(3, 169);
    ((F_CamTriMeshSettings) obj0).\u0002.Name = "cmb_geotype";
    ((F_CamTriMeshSettings) obj0).\u0002.Size = new Size(285, 31 /*0x1F*/);
    ((F_CamTriMeshSettings) obj0).\u0002.TabIndex = 866;
    ((F_CamTriMeshSettings) obj0).\u0002.SelectedIndexChanged += new EventHandler(((buClassViewerColor5) obj0).\u0003);
    ((F_CamTriMeshSettings) obj0).\u0001.AuxInfo = (string) null;
    ((F_CamTriMeshSettings) obj0).\u0001.BackColor = Color.Transparent;
    ((F_CamTriMeshSettings) obj0).\u0001.Caption.Caption = "Image Aligment";
    ((F_CamTriMeshSettings) obj0).\u0001.Caption.Display.BackColor = Color.Silver;
    ((F_CamTriMeshSettings) obj0).\u0001.Caption.Display.Fonts.Alignment = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).\u0001.Caption.Display.Fonts.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).\u0001.Caption.HeightPersentage = 50.0;
    ((F_CamTriMeshSettings) obj0).\u0001.Caption.Visible = true;
    ((F_CamTriMeshSettings) obj0).\u0001.Caption.Width = 140;
    ((F_CamTriMeshSettings) obj0).\u0001.Display.Fonts.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).\u0001.Display.SelectionColor = Color.LightSteelBlue;
    ((F_CamTriMeshSettings) obj0).\u0001.DrawMode = DrawMode.OwnerDrawFixed;
    ((F_CamTriMeshSettings) obj0).\u0001.DropDownStyle = ComboBoxStyle.DropDownList;
    ((F_CamTriMeshSettings) obj0).\u0001.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).\u0001.FormattingEnabled = true;
    ((F_CamTriMeshSettings) obj0).\u0001.Geometry.ArcDiameter = 6;
    ((F_CamTriMeshSettings) obj0).\u0001.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).\u0001.ItemHeight = 25;
    ((F_CamTriMeshSettings) obj0).\u0001.Items.AddRange(new object[4]
    {
      (object) "Solid",
      (object) "Linear Gradient",
      (object) "Center Path Gradient",
      (object) "Interpolated Path Gradient"
    });
    ((F_CamTriMeshSettings) obj0).\u0001.Location = new Point(3, 132);
    ((F_CamTriMeshSettings) obj0).\u0001.Name = "cmb_imagealigment";
    ((F_CamTriMeshSettings) obj0).\u0001.Size = new Size(285, 31 /*0x1F*/);
    ((F_CamTriMeshSettings) obj0).\u0001.TabIndex = 865;
    ((F_CamTriMeshSettings) obj0).\u0001.SelectedIndexChanged += new EventHandler(((buClassViewerColor5) obj0).\u0003);
    ((F_CamTriMeshSettings) obj0).\u0002.BackColor = Color.LightGray;
    ((F_CamTriMeshSettings) obj0).\u0002.Caption = "Button Down";
    ((F_CamTriMeshSettings) obj0).\u0002.Location = new Point(1026, 61);
    ((F_CamTriMeshSettings) obj0).\u0002.Margin = new Padding(2);
    ((F_CamTriMeshSettings) obj0).\u0002.Name = "buControl_DisplayDown";
    ((F_CamTriMeshSettings) obj0).\u0002.Size = new Size(361, 403);
    ((F_CamTriMeshSettings) obj0).\u0002.TabIndex = 815;
    ((F_CamTriMeshSettings) obj0).\u0002.Changed += new EventHandler(((buClassViewerColor5) obj0).\u0002);
    ((F_CamTriMeshSettings) obj0).\u0003.BackColor = Color.LightGray;
    ((F_CamTriMeshSettings) obj0).\u0003.Caption = "Button Over";
    ((F_CamTriMeshSettings) obj0).\u0003.Location = new Point(661, 61);
    ((F_CamTriMeshSettings) obj0).\u0003.Margin = new Padding(2);
    ((F_CamTriMeshSettings) obj0).\u0003.Name = "buControl_DisplayOver";
    ((F_CamTriMeshSettings) obj0).\u0003.Size = new Size(361, 403);
    ((F_CamTriMeshSettings) obj0).\u0003.TabIndex = 814;
    ((F_CamTriMeshSettings) obj0).\u0003.Changed += new EventHandler(((buClassViewerColor5) obj0).\u0002);
    ((F_CamTriMeshSettings) obj0).btn_ref.ButtonCopy = false;
    ((F_CamTriMeshSettings) obj0).btn_ref.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).btn_ref.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).btn_ref.Display.BackColor = Color.DarkGray;
    ((F_CamTriMeshSettings) obj0).btn_ref.Display.Fonts.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_ref.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_ref.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).btn_ref.Image = (Image) componentResourceManager.GetObject("btn_ref.Image");
    ((F_CamTriMeshSettings) obj0).btn_ref.ImageAlign = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).btn_ref.Location = new Point(3, 61);
    ((F_CamTriMeshSettings) obj0).btn_ref.Name = "btn_ref";
    ((F_CamTriMeshSettings) obj0).btn_ref.Size = new Size(285, 59);
    ((F_CamTriMeshSettings) obj0).btn_ref.TabIndex = 813;
    ((F_CamTriMeshSettings) obj0).btn_ref.Text = "Button";
    ((F_CamTriMeshSettings) obj0).btn_ref.UseMnemonic = false;
    ((F_CamTriMeshSettings) obj0).\u0001.BackColor = Color.LightGray;
    ((F_CamTriMeshSettings) obj0).\u0001.Caption = "Button Display";
    ((F_CamTriMeshSettings) obj0).\u0001.Location = new Point(296, 61);
    ((F_CamTriMeshSettings) obj0).\u0001.Margin = new Padding(2);
    ((F_CamTriMeshSettings) obj0).\u0001.Name = "buControl_Display";
    ((F_CamTriMeshSettings) obj0).\u0001.Size = new Size(361, 403);
    ((F_CamTriMeshSettings) obj0).\u0001.TabIndex = 812;
    ((F_CamTriMeshSettings) obj0).\u0001.Changed += new EventHandler(((buClassViewerColor5) obj0).\u0002);
    ((F_CamTriMeshSettings) obj0).btn_ok.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
    ((F_CamTriMeshSettings) obj0).btn_ok.ButtonCopy = false;
    ((F_CamTriMeshSettings) obj0).btn_ok.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).btn_ok.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).btn_ok.Display.BackColor = Color.DarkGray;
    ((F_CamTriMeshSettings) obj0).btn_ok.Display.Fonts.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).btn_ok.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_ok.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).btn_ok.Image = (Image) componentResourceManager.GetObject("btn_ok.Image");
    ((F_CamTriMeshSettings) obj0).btn_ok.ImageAlign = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).btn_ok.Location = new Point(8, 408);
    ((F_CamTriMeshSettings) obj0).btn_ok.Name = "btn_ok";
    ((F_CamTriMeshSettings) obj0).btn_ok.Size = new Size(137, 59);
    ((F_CamTriMeshSettings) obj0).btn_ok.TabIndex = 811;
    ((F_CamTriMeshSettings) obj0).btn_ok.Text = "Ok";
    ((F_CamTriMeshSettings) obj0).btn_ok.UseMnemonic = false;
    ((F_CamTriMeshSettings) obj0).btn_ok.Click += new EventHandler(((buClassViewerColor5) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).btn_cancel.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
    ((F_CamTriMeshSettings) obj0).btn_cancel.ButtonCopy = false;
    ((F_CamTriMeshSettings) obj0).btn_cancel.ButtonDownDisplay.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).btn_cancel.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).btn_cancel.Display.BackColor = Color.DarkGray;
    ((F_CamTriMeshSettings) obj0).btn_cancel.Display.Fonts.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    ((F_CamTriMeshSettings) obj0).btn_cancel.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_cancel.Geometry.ShapeMode = ShapeType.Arc;
    ((F_CamTriMeshSettings) obj0).btn_cancel.Image = (Image) componentResourceManager.GetObject("btn_cancel.Image");
    ((F_CamTriMeshSettings) obj0).btn_cancel.ImageAlign = ContentAlignment.MiddleLeft;
    ((F_CamTriMeshSettings) obj0).btn_cancel.Location = new Point(151, 408);
    ((F_CamTriMeshSettings) obj0).btn_cancel.Name = "btn_cancel";
    ((F_CamTriMeshSettings) obj0).btn_cancel.Size = new Size(137, 59);
    ((F_CamTriMeshSettings) obj0).btn_cancel.TabIndex = 810;
    ((F_CamTriMeshSettings) obj0).btn_cancel.Text = "Cancel";
    ((F_CamTriMeshSettings) obj0).btn_cancel.UseMnemonic = false;
    ((F_CamTriMeshSettings) obj0).btn_cancel.Click += new EventHandler(((buClassViewerColor5) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).btn_close.Anchor = AnchorStyles.Top | AnchorStyles.Right;
    ((F_CamTriMeshSettings) obj0).btn_close.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).btn_close.ButtonCopy = false;
    ((F_CamTriMeshSettings) obj0).btn_close.ButtonDownDisplay.BackColor = Color.Silver;
    ((F_CamTriMeshSettings) obj0).btn_close.ButtonOverDisplay.BackColor = Color.Gray;
    ((F_CamTriMeshSettings) obj0).btn_close.Display.BackColor = Color.DimGray;
    ((F_CamTriMeshSettings) obj0).btn_close.Display.Border.Color = Color.Black;
    ((F_CamTriMeshSettings) obj0).btn_close.Display.Border.Visible = false;
    ((F_CamTriMeshSettings) obj0).btn_close.Display.Fonts.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_close.Font = new Font("Microsoft Sans Serif", 10f);
    ((F_CamTriMeshSettings) obj0).btn_close.Image = (Image) componentResourceManager.GetObject("btn_close.Image");
    ((F_CamTriMeshSettings) obj0).btn_close.Location = new Point(1338, 0);
    ((F_CamTriMeshSettings) obj0).btn_close.Margin = new Padding(4);
    ((F_CamTriMeshSettings) obj0).btn_close.Name = "btn_close";
    ((F_CamTriMeshSettings) obj0).btn_close.Size = new Size(54, 50);
    ((F_CamTriMeshSettings) obj0).btn_close.TabIndex = 220;
    ((F_CamTriMeshSettings) obj0).btn_close.UseMnemonic = false;
    ((F_CamTriMeshSettings) obj0).btn_close.Click += new EventHandler(((buClassViewerColor5) obj0).\u0001);
    obj0.AutoScaleMode = AutoScaleMode.None;
    obj0.ClientSize = new Size(1396, 480);
    obj0.Controls.Add((Control) ((F_CamTriMeshSettings) obj0).buGround1);
    obj0.FormBorderStyle = FormBorderStyle.None;
    obj0.Name = "F_ControlUIButton";
    obj0.Text = "F_MarbleHorizontalCut";
    obj0.FormClosing += new FormClosingEventHandler(((buClassViewerColor5) obj0).\u0001);
    ((F_CamTriMeshSettings) obj0).buGround1.ResumeLayout(false);
    obj0.ResumeLayout(false);
  }
}
