namespace Xbim.Ifc2x3.SharedFacilitiesElements;

public enum IfcServiceLifeFactorTypeEnum : byte
{
	A_QUALITYOFCOMPONENTS,
	B_DESIGNLEVEL,
	C_WORKEXECUTIONLEVEL,
	D_INDOORENVIRONMENT,
	E_OUTDOORENVIRONMENT,
	F_INUSECONDITIONS,
	G_MAINTENANCELEVEL,
	USERDEFINED,
	NOTDEFINED
}
