namespace Xbim.Ifc2x3.HVACDomain;

public enum IfcEvaporatorTypeEnum : byte
{
	DIRECTEXPANSIONSHELLANDTUBE,
	DIRECTEXPANSIONTUBEINTUBE,
	DIRECTEXPANSIONBRAZEDPLATE,
	FLOODEDSHELLANDTUBE,
	SHELLANDCOIL,
	USERDEFINED,
	NOTDEFINED
}
