using System;
using System.Collections.Generic;
using Svg.FilterEffects;

namespace Svg;

internal static class SvgElements
{
	public static Dictionary<Type, string> ElementNames { get; } = new Dictionary<Type, string>
	{
		[typeof(SvgAnchor)] = "a",
		[typeof(SvgCircle)] = "circle",
		[typeof(SvgClipPath)] = "clipPath",
		[typeof(SvgDefinitionList)] = "defs",
		[typeof(SvgDescription)] = "desc",
		[typeof(SvgEllipse)] = "ellipse",
		[typeof(SvgBlend)] = "feBlend",
		[typeof(SvgColourMatrix)] = "feColorMatrix",
		[typeof(SvgComponentTransfer)] = "feComponentTransfer",
		[typeof(SvgComposite)] = "feComposite",
		[typeof(SvgConvolveMatrix)] = "feConvolveMatrix",
		[typeof(SvgDiffuseLighting)] = "feDiffuseLighting",
		[typeof(SvgDisplacementMap)] = "feDisplacementMap",
		[typeof(SvgDistantLight)] = "feDistantLight",
		[typeof(SvgFlood)] = "feFlood",
		[typeof(SvgFuncA)] = "feFuncA",
		[typeof(SvgFuncB)] = "feFuncB",
		[typeof(SvgFuncG)] = "feFuncG",
		[typeof(SvgFuncR)] = "feFuncR",
		[typeof(SvgGaussianBlur)] = "feGaussianBlur",
		[typeof(Svg.FilterEffects.SvgImage)] = "feImage",
		[typeof(SvgMerge)] = "feMerge",
		[typeof(SvgMergeNode)] = "feMergeNode",
		[typeof(SvgMorphology)] = "feMorphology",
		[typeof(SvgOffset)] = "feOffset",
		[typeof(SvgPointLight)] = "fePointLight",
		[typeof(SvgSpecularLighting)] = "feSpecularLighting",
		[typeof(SvgSpotLight)] = "feSpotLight",
		[typeof(SvgTile)] = "feTile",
		[typeof(SvgTurbulence)] = "feTurbulence",
		[typeof(SvgFilter)] = "filter",
		[typeof(SvgFont)] = "font",
		[typeof(SvgFontFace)] = "font-face",
		[typeof(SvgFontFaceSrc)] = "font-face-src",
		[typeof(SvgFontFaceUri)] = "font-face-uri",
		[typeof(SvgForeignObject)] = "foreignObject",
		[typeof(SvgGroup)] = "g",
		[typeof(SvgGlyph)] = "glyph",
		[typeof(SvgHorizontalKern)] = "hkern",
		[typeof(SvgImage)] = "image",
		[typeof(SvgLine)] = "line",
		[typeof(SvgLinearGradientServer)] = "linearGradient",
		[typeof(SvgMarker)] = "marker",
		[typeof(SvgMask)] = "mask",
		[typeof(SvgDocumentMetadata)] = "metadata",
		[typeof(SvgMissingGlyph)] = "missing-glyph",
		[typeof(SvgPath)] = "path",
		[typeof(SvgPatternServer)] = "pattern",
		[typeof(SvgPolygon)] = "polygon",
		[typeof(SvgPolyline)] = "polyline",
		[typeof(SvgRadialGradientServer)] = "radialGradient",
		[typeof(SvgRectangle)] = "rect",
		[typeof(SvgScript)] = "script",
		[typeof(SvgGradientStop)] = "stop",
		[typeof(SvgFragment)] = "svg",
		[typeof(SvgSwitch)] = "switch",
		[typeof(SvgSymbol)] = "symbol",
		[typeof(SvgText)] = "text",
		[typeof(SvgTextPath)] = "textPath",
		[typeof(SvgTitle)] = "title",
		[typeof(SvgTextRef)] = "tref",
		[typeof(SvgTextSpan)] = "tspan",
		[typeof(SvgUse)] = "use",
		[typeof(SvgVerticalKern)] = "vkern"
	};
}
