<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Formats.Asn1</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ILLink.Substitutions.xml" />
    <EmbeddedResource Include="ILLink.Substitutions.xml" LogicalName="ILLink.Substitutions.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Memory">
      <HintPath>..\..\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.ValueTuple">
      <HintPath>..\..\System.ValueTuple.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics" />
    <Reference Include="System.Buffers">
      <HintPath>..\..\System.Buffers.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>