namespace Xbim.Ifc4.Interfaces;

public enum IfcCostScheduleTypeEnum : byte
{
	BUDGET,
	COSTPLAN,
	ESTIMATE,
	TENDER,
	PRICEDBILLOFQUANTITIES,
	UNPRICEDBILLOFQUANTITIES,
	SCHEDULEOFRATES,
	USERDEFINED,
	NOTDEFINED
}
