namespace Xbim.Ifc4.Interfaces;

public enum IfcFlowInstrumentTypeEnum : byte
{
	PRESSUREGAUGE,
	THERMOMETER,
	AMMETER,
	FREQUENCYMETER,
	POWERFACTORMETER,
	PHASEANGLEMETER,
	VOLTMETER_PEAK,
	VOLTMETER_RMS,
	USERDEFINED,
	NOTDEFINED
}
