namespace Xbim.Ifc4.Interfaces;

public enum IfcSwitchingDeviceTypeEnum : byte
{
	CONTACTOR,
	DIMMERSWITCH,
	EMERGENCYSTOP,
	KEYPAD,
	MOMENTARYSWITCH,
	SELECTORSWITCH,
	STARTER,
	SWITCHDISCONNECTOR,
	TOGGLESWITCH,
	USERDEFINED,
	NOTDEFINED
}
