<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Data.SqlClient</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="System.Data.SqlClient.SqlMetaData.xml" />
    <EmbeddedResource Include="System.Data.SqlClient.SqlMetaData.xml" LogicalName="System.Data.SqlClient.SqlMetaData.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>