using System.Runtime.InteropServices;

namespace Opc.Ua.Configuration;

[ComVisible(true)]
public interface IApplicationConfigurationBuilderTransportQuotas : IApplicationConfigurationBuilderServer, IApplicationConfigurationBuilderClient
{
	IApplicationConfigurationBuilderTransportQuotasSet SetTransportQuotas(TransportQuotas transportQuotas);

	IApplicationConfigurationBuilderTransportQuotas SetOperationTimeout(int operationTimeout);

	IApplicationConfigurationBuilderTransportQuotas SetMaxStringLength(int maxStringLength);

	IApplicationConfigurationBuilderTransportQuotas SetMaxByteStringLength(int maxByteStringLength);

	IApplicationConfigurationBuilderTransportQuotas SetMaxArrayLength(int maxArrayLength);

	IApplicationConfigurationBuilderTransportQuotas SetMaxMessageSize(int maxMessageSize);

	IApplicationConfigurationBuilderTransportQuotas SetMaxBufferSize(int maxBufferSize);

	IApplicationConfigurationBuilderTransportQuotas SetChannelLifetime(int channelLifetime);

	IApplicationConfigurationBuilderTransportQuotas SetSecurityTokenLifetime(int securityTokenLifetime);
}
