using System.Runtime.InteropServices;

namespace Opc.Ua.Configuration;

[ComVisible(true)]
public interface IApplicationConfigurationBuilder : IApplicationConfigurationBuilderTypes, IApplicationConfigurationBuilderTransportQuotas, IApplicationConfigurationBuilderServer, IApplicationConfigurationBuilderClient, IApplicationConfigurationBuilderTransportQuotasSet, IApplicationConfigurationBuilderServerSelected, IApplicationConfigurationBuilderServerPolicies, IApplicationConfigurationBuilderServerOptions, IApplicationConfigurationBuilderSecurity, IApplicationConfigurationBuilderClientSelected, IApplicationConfigurationBuilderClientOptions, IApplicationConfigurationBuilderSecurityOptions, IApplicationConfigurationBuilderTraceConfiguration, IApplicationConfigurationBuilderCreate, IApplicationConfigurationBuilderExtension, IApplicationConfigurationBuilderSecurityOptionStores
{
}
