<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UglyToad.PdfPig</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="UglyToad.PdfPig.Resources.CMap.83pv-RKSJ-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.90ms-RKSJ-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.90ms-RKSJ-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.90msp-RKSJ-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.90msp-RKSJ-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.90pv-RKSJ-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.90pv-RKSJ-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Add-RKSJ-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Add-RKSJ-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-0" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-1" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-3" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-4" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-5" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-6" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-UCS2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-0" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-1" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-3" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-4" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-5" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-UCS2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-0" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-1" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-3" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-4" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-5" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-6" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-7" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-UCS2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Japan2-0" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-0" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-1" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-UCS2" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.B5pc-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.B5pc-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.CNS-EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.CNS-EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.ETen-B5-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.ETen-B5-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.ETenms-B5-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.ETenms-B5-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Ext-RKSJ-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Ext-RKSJ-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GB-EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GB-EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBK-EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBK-EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBK2K-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBK2K-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBKp-EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBKp-EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBpc-EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.GBpc-EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.HKscs-B5-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.HKscs-B5-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Identity-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.Identity-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSC-EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSC-EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-HW-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-HW-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSCpc-EUC-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.KSCpc-EUC-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniCNS-UCS2-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniCNS-UCS2-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniCNS-UTF16-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniCNS-UTF16-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniGB-UCS2-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniGB-UCS2-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniGB-UTF16-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniGB-UTF16-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-HW-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-HW-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniJIS-UTF16-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniJIS-UTF16-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniKS-UCS2-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniKS-UCS2-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniKS-UTF16-H" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.UniKS-UTF16-V" />
    <None Remove="UglyToad.PdfPig.Resources.CMap.V" />
    <None Remove="UglyToad.PdfPig.Resources.ICC.sRGB2014.icc" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.83pv-RKSJ-H" LogicalName="UglyToad.PdfPig.Resources.CMap.83pv-RKSJ-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.90ms-RKSJ-H" LogicalName="UglyToad.PdfPig.Resources.CMap.90ms-RKSJ-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.90ms-RKSJ-V" LogicalName="UglyToad.PdfPig.Resources.CMap.90ms-RKSJ-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.90msp-RKSJ-H" LogicalName="UglyToad.PdfPig.Resources.CMap.90msp-RKSJ-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.90msp-RKSJ-V" LogicalName="UglyToad.PdfPig.Resources.CMap.90msp-RKSJ-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.90pv-RKSJ-H" LogicalName="UglyToad.PdfPig.Resources.CMap.90pv-RKSJ-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.90pv-RKSJ-V" LogicalName="UglyToad.PdfPig.Resources.CMap.90pv-RKSJ-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Add-RKSJ-H" LogicalName="UglyToad.PdfPig.Resources.CMap.Add-RKSJ-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Add-RKSJ-V" LogicalName="UglyToad.PdfPig.Resources.CMap.Add-RKSJ-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-0" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-0" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-1" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-1" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-3" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-3" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-4" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-4" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-5" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-5" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-6" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-6" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-UCS2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-CNS1-UCS2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-0" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-0" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-1" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-1" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-3" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-3" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-4" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-4" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-5" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-5" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-UCS2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-GB1-UCS2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-0" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-0" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-1" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-1" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-3" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-3" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-4" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-4" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-5" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-5" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-6" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-6" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-7" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-7" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-UCS2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan1-UCS2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Japan2-0" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Japan2-0" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-0" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-0" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-1" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-1" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-UCS2" LogicalName="UglyToad.PdfPig.Resources.CMap.Adobe-Korea1-UCS2" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.B5pc-H" LogicalName="UglyToad.PdfPig.Resources.CMap.B5pc-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.B5pc-V" LogicalName="UglyToad.PdfPig.Resources.CMap.B5pc-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.CNS-EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.CNS-EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.CNS-EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.CNS-EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.ETen-B5-H" LogicalName="UglyToad.PdfPig.Resources.CMap.ETen-B5-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.ETen-B5-V" LogicalName="UglyToad.PdfPig.Resources.CMap.ETen-B5-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.ETenms-B5-H" LogicalName="UglyToad.PdfPig.Resources.CMap.ETenms-B5-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.ETenms-B5-V" LogicalName="UglyToad.PdfPig.Resources.CMap.ETenms-B5-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Ext-RKSJ-H" LogicalName="UglyToad.PdfPig.Resources.CMap.Ext-RKSJ-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Ext-RKSJ-V" LogicalName="UglyToad.PdfPig.Resources.CMap.Ext-RKSJ-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GB-EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.GB-EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GB-EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.GB-EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBK-EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.GBK-EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBK-EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.GBK-EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBK2K-H" LogicalName="UglyToad.PdfPig.Resources.CMap.GBK2K-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBK2K-V" LogicalName="UglyToad.PdfPig.Resources.CMap.GBK2K-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBKp-EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.GBKp-EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBKp-EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.GBKp-EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBpc-EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.GBpc-EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.GBpc-EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.GBpc-EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.H" LogicalName="UglyToad.PdfPig.Resources.CMap.H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.HKscs-B5-H" LogicalName="UglyToad.PdfPig.Resources.CMap.HKscs-B5-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.HKscs-B5-V" LogicalName="UglyToad.PdfPig.Resources.CMap.HKscs-B5-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Identity-H" LogicalName="UglyToad.PdfPig.Resources.CMap.Identity-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.Identity-V" LogicalName="UglyToad.PdfPig.Resources.CMap.Identity-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSC-EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.KSC-EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSC-EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.KSC-EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-HW-H" LogicalName="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-HW-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-HW-V" LogicalName="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-HW-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.KSCms-UHC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSCpc-EUC-H" LogicalName="UglyToad.PdfPig.Resources.CMap.KSCpc-EUC-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.KSCpc-EUC-V" LogicalName="UglyToad.PdfPig.Resources.CMap.KSCpc-EUC-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniCNS-UCS2-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniCNS-UCS2-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniCNS-UCS2-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniCNS-UCS2-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniCNS-UTF16-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniCNS-UTF16-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniCNS-UTF16-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniCNS-UTF16-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniGB-UCS2-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniGB-UCS2-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniGB-UCS2-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniGB-UCS2-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniGB-UTF16-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniGB-UTF16-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniGB-UTF16-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniGB-UTF16-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-HW-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-HW-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-HW-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-HW-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniJIS-UCS2-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniJIS-UTF16-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniJIS-UTF16-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniJIS-UTF16-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniJIS-UTF16-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniKS-UCS2-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniKS-UCS2-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniKS-UCS2-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniKS-UCS2-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniKS-UTF16-H" LogicalName="UglyToad.PdfPig.Resources.CMap.UniKS-UTF16-H" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.UniKS-UTF16-V" LogicalName="UglyToad.PdfPig.Resources.CMap.UniKS-UTF16-V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.CMap.V" LogicalName="UglyToad.PdfPig.Resources.CMap.V" />
    <EmbeddedResource Include="UglyToad.PdfPig.Resources.ICC.sRGB2014.icc" LogicalName="UglyToad.PdfPig.Resources.ICC.sRGB2014.icc" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Memory">
      <HintPath>..\..\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="UglyToad.PdfPig.Tokens">
      <HintPath>..\..\UglyToad.PdfPig.Tokens.dll</HintPath>
    </Reference>
    <Reference Include="UglyToad.PdfPig.Core">
      <HintPath>..\..\UglyToad.PdfPig.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="UglyToad.PdfPig.Fonts">
      <HintPath>..\..\UglyToad.PdfPig.Fonts.dll</HintPath>
    </Reference>
    <Reference Include="UglyToad.PdfPig.Tokenization">
      <HintPath>..\..\UglyToad.PdfPig.Tokenization.dll</HintPath>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>..\..\System.Buffers.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Bcl.HashCode">
      <HintPath>..\..\Microsoft.Bcl.HashCode.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>