// Decompiled with JetBrains decompiler
// Type: MarbleCNC.F_Menu
// Assembly: CMDMarbleCNC, Version=3.1.1.1, Culture=neutral, PublicKeyToken=null
// MVID: 99805DCC-380E-4FBC-B708-84554BBCD25B
// Assembly location: C:\Users\ERCAN\Desktop\CMDMarbleCNC\CMDMarbleCNC.exe

using buClass;
using buControls.Controls;
using buEyeBaseVer5;
using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

#nullable disable
namespace MarbleCNC;

public class F_Menu : Form
{
  public FormProperties PropertiesForm = new FormProperties();
  private IContainer components = (IContainer) null;
  private buGround buGround1;
  public buButton btn_password;
  public buButton btn_report;
  public buButton btn_test;
  public buButton btn_tools;
  public buButton btn_settings;
  public buButton btn_simulationpanel;
  public buButton btn_closepc;
  public buButton btn_selectmaterial;
  public buButton btn_g54offset;
  public buButton btn_calculations;
  public buButton btn_maintanance;
  public buButton btn_warmup;
  public buButton btn_materialmeasurement;
  public buButton btn_adminsettings;
  public buButton btn_cancel;

  public F_Menu() => this.InitializeComponent();

  private void btn_ok_Click(object sender, EventArgs e)
  {
  }

  public void InitVisual()
  {
    if (new FileInfo(AppPath.MachineSettings + "\\ApplicationVisual.prm").Exists)
    {
      Control.ControlCollection controlCollection = (Control.ControlCollection) null;
      controlCollection = hmiUICommands.SetVisualItem(this.buGround1.Controls);
    }
    this.PropertiesForm.VisualUpdated = true;
  }

  public void LoadLanguage()
  {
    this.buGround1.Text = buLangTranslate.preDef.Menu;
    this.btn_closepc.Text = buLangTranslate.preDef.Close + " PC";
    this.btn_password.Text = buLangTranslate.preDef.Password;
    this.btn_report.Text = buLangTranslate.preDef.Report;
    this.btn_selectmaterial.Text = $"{buLangTranslate.preDef.Material} {buLangTranslate.preDef.Select}";
    this.btn_settings.Text = buLangTranslate.preDef.Settings;
    this.btn_simulationpanel.Text = buLangTranslate.preDef.Simulation;
    this.btn_test.Text = buLangTranslate.preDef.Test;
    this.btn_tools.Text = $"{buLangTranslate.preDef.Tools} {buLangTranslate.preDef.List}";
    this.btn_g54offset.Text = $"{buLangTranslate.preChar.G54} {buLangTranslate.preDef.Offset}";
    this.btn_adminsettings.Text = $"{buLangTranslate.preDef.Admin} {buLangTranslate.preDef.Settings}";
    this.btn_maintanance.Text = buLangTranslate.preDef.Maintanance;
    this.btn_materialmeasurement.Text = $"{buLangTranslate.preDef.Material} {buLangTranslate.preDef.Measure}";
    this.btn_calculations.Text = buLangTranslate.preDef.Calculate;
  }

  private void btn_cancel_Click(object sender, EventArgs e) => this.Visible = false;

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.components != null)
      this.components.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (F_Menu));
    this.buGround1 = new buGround();
    this.btn_cancel = new buButton();
    this.btn_adminsettings = new buButton();
    this.btn_materialmeasurement = new buButton();
    this.btn_warmup = new buButton();
    this.btn_maintanance = new buButton();
    this.btn_calculations = new buButton();
    this.btn_g54offset = new buButton();
    this.btn_selectmaterial = new buButton();
    this.btn_closepc = new buButton();
    this.btn_simulationpanel = new buButton();
    this.btn_settings = new buButton();
    this.btn_tools = new buButton();
    this.btn_password = new buButton();
    this.btn_report = new buButton();
    this.btn_test = new buButton();
    this.buGround1.SuspendLayout();
    this.SuspendLayout();
    this.buGround1.AuxInfo = (string) null;
    this.buGround1.BackColor = Color.Transparent;
    this.buGround1.Controls.Add((Control) this.btn_cancel);
    this.buGround1.Controls.Add((Control) this.btn_adminsettings);
    this.buGround1.Controls.Add((Control) this.btn_materialmeasurement);
    this.buGround1.Controls.Add((Control) this.btn_warmup);
    this.buGround1.Controls.Add((Control) this.btn_maintanance);
    this.buGround1.Controls.Add((Control) this.btn_calculations);
    this.buGround1.Controls.Add((Control) this.btn_g54offset);
    this.buGround1.Controls.Add((Control) this.btn_selectmaterial);
    this.buGround1.Controls.Add((Control) this.btn_closepc);
    this.buGround1.Controls.Add((Control) this.btn_simulationpanel);
    this.buGround1.Controls.Add((Control) this.btn_settings);
    this.buGround1.Controls.Add((Control) this.btn_tools);
    this.buGround1.Controls.Add((Control) this.btn_password);
    this.buGround1.Controls.Add((Control) this.btn_report);
    this.buGround1.Controls.Add((Control) this.btn_test);
    this.buGround1.ControlStyle = ControlStyle.Base3;
    this.buGround1.Display.Fonts.Font = new Font("Microsoft Sans Serif", 10f);
    this.buGround1.Display.GradientType = GradientMode.Lineer;
    this.buGround1.Display.LineerGradient.FirstColor = Color.Black;
    this.buGround1.DisplayBottom.BackColor = Color.Gray;
    this.buGround1.DisplayTop.BackColor = Color.DimGray;
    this.buGround1.Dock = DockStyle.Fill;
    this.buGround1.Font = new Font("Microsoft Sans Serif", 10f);
    this.buGround1.Ground.TopHeight = 50;
    this.buGround1.Image = (Image) null;
    this.buGround1.ImageAlign = ContentAlignment.MiddleLeft;
    this.buGround1.Location = new Point(0, 0);
    this.buGround1.Name = "buGround1";
    this.buGround1.Sizable = true;
    this.buGround1.Size = new Size(604, 679);
    this.buGround1.SmartBounds = true;
    this.buGround1.StartPosition = FormStartPosition.Manual;
    this.buGround1.TabIndex = 1;
    this.buGround1.Text = "Menü";
    this.btn_cancel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
    this.btn_cancel.BackColor = Color.DimGray;
    this.btn_cancel.ButtonCopy = false;
    this.btn_cancel.ButtonDownDisplay.BackColor = Color.Silver;
    this.btn_cancel.ButtonOverDisplay.BackColor = Color.Gray;
    this.btn_cancel.ControlStyle = ControlStyle.FormButton;
    this.btn_cancel.Display.BackColor = Color.DimGray;
    this.btn_cancel.Display.Border.Color = Color.Black;
    this.btn_cancel.Display.Border.Visible = false;
    this.btn_cancel.Display.Fonts.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_cancel.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_cancel.Image = (Image) componentResourceManager.GetObject("btn_cancel.Image");
    this.btn_cancel.Location = new Point(550, 0);
    this.btn_cancel.Margin = new Padding(4);
    this.btn_cancel.Name = "btn_cancel";
    this.btn_cancel.Size = new Size(54, 50);
    this.btn_cancel.TabIndex = 595;
    this.btn_cancel.UseMnemonic = false;
    this.btn_cancel.Click += new EventHandler(this.btn_cancel_Click);
    this.btn_adminsettings.BackColor = Color.Transparent;
    this.btn_adminsettings.ButtonCopy = false;
    this.btn_adminsettings.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_adminsettings.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_adminsettings.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_adminsettings.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_adminsettings.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_adminsettings.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_adminsettings.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_adminsettings.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_adminsettings.ControlStyle = ControlStyle.Menu3;
    this.btn_adminsettings.Display.BackColor = Color.PeachPuff;
    this.btn_adminsettings.Display.Border.Color = Color.Black;
    this.btn_adminsettings.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_adminsettings.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_adminsettings.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_adminsettings.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_adminsettings.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_adminsettings.Image = (Image) componentResourceManager.GetObject("btn_adminsettings.Image");
    this.btn_adminsettings.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_adminsettings.Location = new Point(312, 499);
    this.btn_adminsettings.Name = "btn_adminsettings";
    this.btn_adminsettings.Size = new Size(280, 75);
    this.btn_adminsettings.TabIndex = 594;
    this.btn_adminsettings.Text = "Admin Settings";
    this.btn_adminsettings.UseMnemonic = false;
    this.btn_materialmeasurement.BackColor = Color.Transparent;
    this.btn_materialmeasurement.ButtonCopy = false;
    this.btn_materialmeasurement.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_materialmeasurement.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_materialmeasurement.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_materialmeasurement.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_materialmeasurement.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_materialmeasurement.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_materialmeasurement.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_materialmeasurement.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_materialmeasurement.ControlStyle = ControlStyle.Menu3;
    this.btn_materialmeasurement.Display.BackColor = Color.PeachPuff;
    this.btn_materialmeasurement.Display.Border.Color = Color.Black;
    this.btn_materialmeasurement.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_materialmeasurement.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_materialmeasurement.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_materialmeasurement.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_materialmeasurement.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_materialmeasurement.Image = (Image) componentResourceManager.GetObject("btn_materialmeasurement.Image");
    this.btn_materialmeasurement.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_materialmeasurement.Location = new Point(311, 323);
    this.btn_materialmeasurement.Name = "btn_materialmeasurement";
    this.btn_materialmeasurement.Size = new Size(280, 75);
    this.btn_materialmeasurement.TabIndex = 593;
    this.btn_materialmeasurement.Text = "Material Measure";
    this.btn_materialmeasurement.UseMnemonic = false;
    this.btn_warmup.BackColor = Color.Transparent;
    this.btn_warmup.ButtonCopy = false;
    this.btn_warmup.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_warmup.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_warmup.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_warmup.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_warmup.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_warmup.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_warmup.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_warmup.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_warmup.ControlStyle = ControlStyle.Menu3;
    this.btn_warmup.Display.BackColor = Color.PeachPuff;
    this.btn_warmup.Display.Border.Color = Color.Black;
    this.btn_warmup.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_warmup.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_warmup.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_warmup.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_warmup.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_warmup.Image = (Image) componentResourceManager.GetObject("btn_warmup.Image");
    this.btn_warmup.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_warmup.Location = new Point(311, 412);
    this.btn_warmup.Name = "btn_warmup";
    this.btn_warmup.Size = new Size(280, 75);
    this.btn_warmup.TabIndex = 592;
    this.btn_warmup.Text = "Warm Up";
    this.btn_warmup.UseMnemonic = false;
    this.btn_maintanance.BackColor = Color.Transparent;
    this.btn_maintanance.ButtonCopy = false;
    this.btn_maintanance.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_maintanance.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_maintanance.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_maintanance.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_maintanance.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_maintanance.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_maintanance.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_maintanance.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_maintanance.ControlStyle = ControlStyle.Menu3;
    this.btn_maintanance.Display.BackColor = Color.PeachPuff;
    this.btn_maintanance.Display.Border.Color = Color.Black;
    this.btn_maintanance.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_maintanance.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_maintanance.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_maintanance.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_maintanance.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_maintanance.Image = (Image) componentResourceManager.GetObject("btn_maintanance.Image");
    this.btn_maintanance.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_maintanance.Location = new Point(12, 323);
    this.btn_maintanance.Name = "btn_maintanance";
    this.btn_maintanance.Size = new Size(280, 75);
    this.btn_maintanance.TabIndex = 590;
    this.btn_maintanance.Text = "Maintanance";
    this.btn_maintanance.UseMnemonic = false;
    this.btn_calculations.BackColor = Color.Transparent;
    this.btn_calculations.ButtonCopy = false;
    this.btn_calculations.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_calculations.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_calculations.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_calculations.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_calculations.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_calculations.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_calculations.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_calculations.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_calculations.ControlStyle = ControlStyle.Menu3;
    this.btn_calculations.Display.BackColor = Color.PeachPuff;
    this.btn_calculations.Display.Border.Color = Color.Black;
    this.btn_calculations.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_calculations.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_calculations.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_calculations.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_calculations.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_calculations.Image = (Image) componentResourceManager.GetObject("btn_calculations.Image");
    this.btn_calculations.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_calculations.Location = new Point(312, 587);
    this.btn_calculations.Name = "btn_calculations";
    this.btn_calculations.Size = new Size(280, 75);
    this.btn_calculations.TabIndex = 589;
    this.btn_calculations.Text = "Calculations";
    this.btn_calculations.UseMnemonic = false;
    this.btn_g54offset.BackColor = Color.Transparent;
    this.btn_g54offset.ButtonCopy = false;
    this.btn_g54offset.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_g54offset.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_g54offset.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_g54offset.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_g54offset.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_g54offset.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_g54offset.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_g54offset.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_g54offset.ControlStyle = ControlStyle.Menu3;
    this.btn_g54offset.Display.BackColor = Color.PeachPuff;
    this.btn_g54offset.Display.Border.Color = Color.Black;
    this.btn_g54offset.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_g54offset.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_g54offset.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_g54offset.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_g54offset.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_g54offset.Image = (Image) componentResourceManager.GetObject("btn_g54offset.Image");
    this.btn_g54offset.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_g54offset.Location = new Point(12, 148);
    this.btn_g54offset.Name = "btn_g54offset";
    this.btn_g54offset.Size = new Size(280, 75);
    this.btn_g54offset.TabIndex = 587;
    this.btn_g54offset.Text = "G54 Offsets";
    this.btn_g54offset.UseMnemonic = false;
    this.btn_selectmaterial.BackColor = Color.Transparent;
    this.btn_selectmaterial.ButtonCopy = false;
    this.btn_selectmaterial.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_selectmaterial.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_selectmaterial.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_selectmaterial.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_selectmaterial.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_selectmaterial.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_selectmaterial.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_selectmaterial.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_selectmaterial.ControlStyle = ControlStyle.Menu3;
    this.btn_selectmaterial.Display.BackColor = Color.PeachPuff;
    this.btn_selectmaterial.Display.Border.Color = Color.Black;
    this.btn_selectmaterial.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_selectmaterial.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_selectmaterial.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_selectmaterial.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_selectmaterial.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_selectmaterial.Image = (Image) componentResourceManager.GetObject("btn_selectmaterial.Image");
    this.btn_selectmaterial.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_selectmaterial.Location = new Point(12, 412);
    this.btn_selectmaterial.Name = "btn_selectmaterial";
    this.btn_selectmaterial.Size = new Size(280, 75);
    this.btn_selectmaterial.TabIndex = 585;
    this.btn_selectmaterial.Text = "Select Material";
    this.btn_selectmaterial.UseMnemonic = false;
    this.btn_closepc.BackColor = Color.Transparent;
    this.btn_closepc.ButtonCopy = false;
    this.btn_closepc.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_closepc.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_closepc.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_closepc.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_closepc.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_closepc.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_closepc.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_closepc.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_closepc.ControlStyle = ControlStyle.Menu3;
    this.btn_closepc.Display.BackColor = Color.PeachPuff;
    this.btn_closepc.Display.Border.Color = Color.Black;
    this.btn_closepc.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_closepc.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_closepc.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_closepc.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_closepc.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_closepc.Image = (Image) componentResourceManager.GetObject("btn_closepc.Image");
    this.btn_closepc.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_closepc.Location = new Point(12, 587);
    this.btn_closepc.Name = "btn_closepc";
    this.btn_closepc.Size = new Size(280, 75);
    this.btn_closepc.TabIndex = 584;
    this.btn_closepc.Text = "Close PC";
    this.btn_closepc.UseMnemonic = false;
    this.btn_simulationpanel.BackColor = Color.Transparent;
    this.btn_simulationpanel.ButtonCopy = false;
    this.btn_simulationpanel.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_simulationpanel.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_simulationpanel.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_simulationpanel.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_simulationpanel.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_simulationpanel.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_simulationpanel.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_simulationpanel.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_simulationpanel.ControlStyle = ControlStyle.Menu3;
    this.btn_simulationpanel.Display.BackColor = Color.PeachPuff;
    this.btn_simulationpanel.Display.Border.Color = Color.Black;
    this.btn_simulationpanel.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_simulationpanel.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_simulationpanel.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_simulationpanel.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_simulationpanel.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_simulationpanel.Image = (Image) componentResourceManager.GetObject("btn_simulationpanel.Image");
    this.btn_simulationpanel.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_simulationpanel.Location = new Point(12, 499);
    this.btn_simulationpanel.Name = "btn_simulationpanel";
    this.btn_simulationpanel.Size = new Size(280, 75);
    this.btn_simulationpanel.TabIndex = 582;
    this.btn_simulationpanel.Text = "Simulation Panel";
    this.btn_simulationpanel.UseMnemonic = false;
    this.btn_settings.BackColor = Color.Transparent;
    this.btn_settings.ButtonCopy = false;
    this.btn_settings.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_settings.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_settings.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_settings.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_settings.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_settings.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_settings.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_settings.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_settings.ControlStyle = ControlStyle.Menu3;
    this.btn_settings.Display.BackColor = Color.PeachPuff;
    this.btn_settings.Display.Border.Color = Color.Black;
    this.btn_settings.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_settings.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_settings.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_settings.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_settings.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_settings.Image = (Image) componentResourceManager.GetObject("btn_settings.Image");
    this.btn_settings.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_settings.Location = new Point(12, 60);
    this.btn_settings.Name = "btn_settings";
    this.btn_settings.Size = new Size(280, 75);
    this.btn_settings.TabIndex = 579;
    this.btn_settings.Text = "Settings";
    this.btn_settings.UseMnemonic = false;
    this.btn_tools.BackColor = Color.Transparent;
    this.btn_tools.ButtonCopy = false;
    this.btn_tools.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_tools.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_tools.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_tools.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_tools.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_tools.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_tools.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_tools.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_tools.ControlStyle = ControlStyle.Menu3;
    this.btn_tools.Display.BackColor = Color.PeachPuff;
    this.btn_tools.Display.Border.Color = Color.Black;
    this.btn_tools.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_tools.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_tools.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_tools.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_tools.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_tools.Image = (Image) componentResourceManager.GetObject("btn_tools.Image");
    this.btn_tools.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_tools.Location = new Point(311, 148);
    this.btn_tools.Name = "btn_tools";
    this.btn_tools.Size = new Size(280, 75);
    this.btn_tools.TabIndex = 575;
    this.btn_tools.Text = "Tools List";
    this.btn_tools.UseMnemonic = false;
    this.btn_password.BackColor = Color.Transparent;
    this.btn_password.ButtonCopy = false;
    this.btn_password.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_password.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_password.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_password.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_password.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_password.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_password.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_password.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_password.ControlStyle = ControlStyle.Menu3;
    this.btn_password.Display.BackColor = Color.PeachPuff;
    this.btn_password.Display.Border.Color = Color.Black;
    this.btn_password.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_password.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_password.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_password.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_password.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_password.Image = (Image) componentResourceManager.GetObject("btn_password.Image");
    this.btn_password.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_password.Location = new Point(12, 234);
    this.btn_password.Name = "btn_password";
    this.btn_password.Size = new Size(280, 75);
    this.btn_password.TabIndex = 569;
    this.btn_password.Text = "Şifre";
    this.btn_password.UseMnemonic = false;
    this.btn_report.BackColor = Color.Transparent;
    this.btn_report.ButtonCopy = false;
    this.btn_report.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_report.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_report.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_report.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_report.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_report.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_report.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_report.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_report.ControlStyle = ControlStyle.Menu3;
    this.btn_report.Display.BackColor = Color.PeachPuff;
    this.btn_report.Display.Border.Color = Color.Black;
    this.btn_report.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_report.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_report.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_report.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_report.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_report.Image = (Image) componentResourceManager.GetObject("btn_report.Image");
    this.btn_report.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_report.Location = new Point(311, 234);
    this.btn_report.Name = "btn_report";
    this.btn_report.Size = new Size(280, 75);
    this.btn_report.TabIndex = 568;
    this.btn_report.Text = "Rapor";
    this.btn_report.UseMnemonic = false;
    this.btn_test.BackColor = Color.Transparent;
    this.btn_test.ButtonCopy = false;
    this.btn_test.ButtonDownDisplay.BackColor = Color.Gold;
    this.btn_test.ButtonDownDisplay.Border.Color = Color.Black;
    this.btn_test.ButtonDownDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_test.ButtonDownDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_test.ButtonOverDisplay.BackColor = Color.Gainsboro;
    this.btn_test.ButtonOverDisplay.Border.Color = Color.Black;
    this.btn_test.ButtonOverDisplay.Fonts.Font = new Font("Arial", 11.25f, FontStyle.Bold);
    this.btn_test.ButtonOverDisplay.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_test.ControlStyle = ControlStyle.Menu3;
    this.btn_test.Display.BackColor = Color.PeachPuff;
    this.btn_test.Display.Border.Color = Color.Black;
    this.btn_test.Display.Fonts.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 162);
    this.btn_test.Display.Fonts.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_test.Font = new Font("Microsoft Sans Serif", 10f);
    this.btn_test.ForeColor = Color.FromArgb(0, 27, 72);
    this.btn_test.Geometry.ShapeMode = ShapeType.Arc;
    this.btn_test.Image = (Image) componentResourceManager.GetObject("btn_test.Image");
    this.btn_test.ImageAlign = ContentAlignment.MiddleLeft;
    this.btn_test.Location = new Point(311, 60);
    this.btn_test.Name = "btn_test";
    this.btn_test.Size = new Size(280, 75);
    this.btn_test.TabIndex = 565;
    this.btn_test.Text = "Test";
    this.btn_test.UseMnemonic = false;
    this.AutoScaleMode = AutoScaleMode.None;
    this.ClientSize = new Size(604, 679);
    this.Controls.Add((Control) this.buGround1);
    this.FormBorderStyle = FormBorderStyle.None;
    this.Name = nameof (F_Menu);
    this.Text = "Menu";
    this.buGround1.ResumeLayout(false);
    this.ResumeLayout(false);
  }
}
