<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Svg</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Svg.Resources.svg11.dtd" />
    <EmbeddedResource Include="Svg.Resources.svg11.dtd" LogicalName="Svg.Resources.svg11.dtd" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Memory">
      <HintPath>..\..\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="ExCSS">
      <HintPath>..\..\ExCSS.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>