using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using buClass;
using buControls.Controls;
using buEyeBaseVer5;

namespace MarbleCNC;

public class F_MenuSettings : Form
{
	public FormProperties PropertiesForm = new FormProperties();

	private IContainer components = null;

	private buGround buGround1;

	public buButton btn_kinematic;

	public buButton btn_AbsoluteHomeSet;

	public buButton btn_G54Offset;

	public buButton btn_GantryPage;

	public buButton btn_settingsaxes;

	public buButton btn_marblecamsettings;

	public buButton btn_millingsettings;

	public buButton btn_servoconnection;

	public buButton btn_calibration;

	public buButton btn_camerasettings;

	public buButton btn_vagoonsettings;

	public buButton btn_toolsettings;

	public buButton btn_axesgain;

	public buButton btn_cameracalibration;

	public buButton btn_machinedefination;

	public buButton btn_programsettings;

	public buButton btn_circulargeometry;

	public buButton btn_cancel;

	public buButton btn_circularspeedreduce;

	public F_MenuSettings()
	{
		InitializeComponent();
	}

	public void Init()
	{
	}

	public void InitVisual()
	{
		FileInfo fileInfo = new FileInfo(AppPath.MachineSettings + "\\ApplicationVisual.prm");
		if (fileInfo.Exists)
		{
			Control.ControlCollection controlCollection = null;
			controlCollection = buGround1.Controls;
			controlCollection = hmiUICommands.SetVisualItem(controlCollection);
		}
		PropertiesForm.VisualUpdated = true;
	}

	private void btn_ok_Click(object sender, EventArgs e)
	{
	}

	public void LoadLanguage()
	{
		buGround1.Text = buLangTranslate.preDef.Setting + " " + buLangTranslate.preDef.Menu;
		btn_AbsoluteHomeSet.Text = buLangTranslate.preDef.Axes + " " + buLangTranslate.preDef.Absolute + " " + buLangTranslate.preDef.Home;
		btn_G54Offset.Text = "G54 " + buLangTranslate.preDef.Part + " " + buLangTranslate.preDef.Offset;
		btn_GantryPage.Text = buLangTranslate.preDef.Gantry + " " + buLangTranslate.preDef.Setting;
		btn_kinematic.Text = buLangTranslate.preDef.Kinematic + " " + buLangTranslate.preDef.Setting;
		btn_marblecamsettings.Text = buLangTranslate.preDef.Marble + " " + buLangTranslate.preDef.Cam + " " + buLangTranslate.preDef.Setting;
		btn_millingsettings.Text = buLangTranslate.preDef.Milling + " " + buLangTranslate.preDef.Setting;
		btn_settingsaxes.Text = "CNC - " + buLangTranslate.preDef.Axes + " " + buLangTranslate.preDef.Setting;
		btn_cameracalibration.Text = buLangTranslate.preDef.Camera + " " + buLangTranslate.preDef.Calibration;
		btn_toolsettings.Text = buLangTranslate.preDef.Machine + " " + buLangTranslate.preDef.Settings;
		btn_camerasettings.Text = buLangTranslate.preDef.Camera + " " + buLangTranslate.preDef.Settings;
		btn_vagoonsettings.Text = buLangTranslate.preDef.Trolley + " " + buLangTranslate.preDef.Settings;
		btn_servoconnection.Text = buLangTranslate.preDef.Servo + " " + buLangTranslate.preDef.Connection;
		btn_axesgain.Text = buLangTranslate.preDef.Axes + " " + buLangTranslate.preDef.Gain;
		btn_calibration.Text = buLangTranslate.preDef.Machine + " " + buLangTranslate.preDef.Calibration;
		btn_programsettings.Text = buLangTranslate.preDef.Program + " " + buLangTranslate.preDef.Settings;
		btn_machinedefination.Text = buLangTranslate.preDef.Trolley + " " + buLangTranslate.preDef.Define;
		btn_circulargeometry.Text = buLangTranslate.preDef.Circular + " " + buLangTranslate.preDef.Geometry;
		btn_circularspeedreduce.Text = buLangTranslate.preDef.Circular + " " + buLangTranslate.preDef.Speed + " " + buLangTranslate.preDef.Reduction;
	}

	private void btn_cancel_Click(object sender, EventArgs e)
	{
		base.Visible = false;
	}

	protected override void Dispose(bool disposing)
	{
		if (disposing && components != null)
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	private void InitializeComponent()
	{
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MarbleCNC.F_MenuSettings));
		this.buGround1 = new buControls.Controls.buGround();
		this.btn_cancel = new buControls.Controls.buButton();
		this.btn_circulargeometry = new buControls.Controls.buButton();
		this.btn_programsettings = new buControls.Controls.buButton();
		this.btn_machinedefination = new buControls.Controls.buButton();
		this.btn_cameracalibration = new buControls.Controls.buButton();
		this.btn_axesgain = new buControls.Controls.buButton();
		this.btn_camerasettings = new buControls.Controls.buButton();
		this.btn_vagoonsettings = new buControls.Controls.buButton();
		this.btn_toolsettings = new buControls.Controls.buButton();
		this.btn_calibration = new buControls.Controls.buButton();
		this.btn_servoconnection = new buControls.Controls.buButton();
		this.btn_millingsettings = new buControls.Controls.buButton();
		this.btn_marblecamsettings = new buControls.Controls.buButton();
		this.btn_AbsoluteHomeSet = new buControls.Controls.buButton();
		this.btn_G54Offset = new buControls.Controls.buButton();
		this.btn_GantryPage = new buControls.Controls.buButton();
		this.btn_settingsaxes = new buControls.Controls.buButton();
		this.btn_kinematic = new buControls.Controls.buButton();
		this.btn_circularspeedreduce = new buControls.Controls.buButton();
		this.buGround1.SuspendLayout();
		base.SuspendLayout();
		this.buGround1.AuxInfo = null;
		this.buGround1.BackColor = System.Drawing.Color.Transparent;
		this.buGround1.Controls.Add(this.btn_circularspeedreduce);
		this.buGround1.Controls.Add(this.btn_cancel);
		this.buGround1.Controls.Add(this.btn_circulargeometry);
		this.buGround1.Controls.Add(this.btn_programsettings);
		this.buGround1.Controls.Add(this.btn_machinedefination);
		this.buGround1.Controls.Add(this.btn_cameracalibration);
		this.buGround1.Controls.Add(this.btn_axesgain);
		this.buGround1.Controls.Add(this.btn_camerasettings);
		this.buGround1.Controls.Add(this.btn_vagoonsettings);
		this.buGround1.Controls.Add(this.btn_toolsettings);
		this.buGround1.Controls.Add(this.btn_calibration);
		this.buGround1.Controls.Add(this.btn_servoconnection);
		this.buGround1.Controls.Add(this.btn_millingsettings);
		this.buGround1.Controls.Add(this.btn_marblecamsettings);
		this.buGround1.Controls.Add(this.btn_AbsoluteHomeSet);
		this.buGround1.Controls.Add(this.btn_G54Offset);
		this.buGround1.Controls.Add(this.btn_GantryPage);
		this.buGround1.Controls.Add(this.btn_settingsaxes);
		this.buGround1.Controls.Add(this.btn_kinematic);
		this.buGround1.ControlStyle = buControls.Controls.ControlStyle.Base4;
		this.buGround1.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.buGround1.Display.GradientType = buControls.Controls.GradientMode.Lineer;
		this.buGround1.Display.LineerGradient.FirstColor = System.Drawing.Color.Black;
		this.buGround1.DisplayBottom.BackColor = System.Drawing.Color.Gray;
		this.buGround1.DisplayTop.BackColor = System.Drawing.Color.DimGray;
		this.buGround1.Dock = System.Windows.Forms.DockStyle.Fill;
		this.buGround1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.buGround1.Ground.TopHeight = 50;
		this.buGround1.Image = null;
		this.buGround1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.buGround1.Location = new System.Drawing.Point(0, 0);
		this.buGround1.Name = "buGround1";
		this.buGround1.Sizable = true;
		this.buGround1.Size = new System.Drawing.Size(892, 628);
		this.buGround1.SmartBounds = true;
		this.buGround1.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
		this.buGround1.TabIndex = 1;
		this.buGround1.Text = "Settings";
		this.btn_cancel.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
		this.btn_cancel.BackColor = System.Drawing.Color.DimGray;
		this.btn_cancel.ButtonCopy = false;
		this.btn_cancel.ButtonDownDisplay.BackColor = System.Drawing.Color.Silver;
		this.btn_cancel.ButtonOverDisplay.BackColor = System.Drawing.Color.Gray;
		this.btn_cancel.ControlStyle = buControls.Controls.ControlStyle.FormButton;
		this.btn_cancel.Display.BackColor = System.Drawing.Color.DimGray;
		this.btn_cancel.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_cancel.Display.Border.Visible = false;
		this.btn_cancel.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_cancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_cancel.Image = (System.Drawing.Image)resources.GetObject("btn_cancel.Image");
		this.btn_cancel.Location = new System.Drawing.Point(838, 0);
		this.btn_cancel.Margin = new System.Windows.Forms.Padding(4);
		this.btn_cancel.Name = "btn_cancel";
		this.btn_cancel.Size = new System.Drawing.Size(54, 50);
		this.btn_cancel.TabIndex = 592;
		this.btn_cancel.UseMnemonic = false;
		this.btn_cancel.Click += new System.EventHandler(btn_cancel_Click);
		this.btn_circulargeometry.BackColor = System.Drawing.Color.Transparent;
		this.btn_circulargeometry.ButtonCopy = false;
		this.btn_circulargeometry.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_circulargeometry.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_circulargeometry.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_circulargeometry.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circulargeometry.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_circulargeometry.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_circulargeometry.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_circulargeometry.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circulargeometry.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_circulargeometry.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_circulargeometry.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_circulargeometry.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_circulargeometry.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circulargeometry.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_circulargeometry.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circulargeometry.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_circulargeometry.Image = (System.Drawing.Image)resources.GetObject("btn_circulargeometry.Image");
		this.btn_circulargeometry.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_circulargeometry.Location = new System.Drawing.Point(304, 535);
		this.btn_circulargeometry.Name = "btn_circulargeometry";
		this.btn_circulargeometry.Size = new System.Drawing.Size(280, 75);
		this.btn_circulargeometry.TabIndex = 591;
		this.btn_circulargeometry.Text = "Circular Geometry";
		this.btn_circulargeometry.UseMnemonic = false;
		this.btn_programsettings.BackColor = System.Drawing.Color.Transparent;
		this.btn_programsettings.ButtonCopy = false;
		this.btn_programsettings.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_programsettings.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_programsettings.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_programsettings.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_programsettings.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_programsettings.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_programsettings.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_programsettings.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_programsettings.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_programsettings.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_programsettings.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_programsettings.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_programsettings.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_programsettings.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_programsettings.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_programsettings.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_programsettings.Image = (System.Drawing.Image)resources.GetObject("btn_programsettings.Image");
		this.btn_programsettings.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_programsettings.Location = new System.Drawing.Point(304, 158);
		this.btn_programsettings.Name = "btn_programsettings";
		this.btn_programsettings.Size = new System.Drawing.Size(280, 75);
		this.btn_programsettings.TabIndex = 590;
		this.btn_programsettings.Text = "Program Settings";
		this.btn_programsettings.UseMnemonic = false;
		this.btn_machinedefination.BackColor = System.Drawing.Color.Transparent;
		this.btn_machinedefination.ButtonCopy = false;
		this.btn_machinedefination.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_machinedefination.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_machinedefination.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_machinedefination.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_machinedefination.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_machinedefination.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_machinedefination.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_machinedefination.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_machinedefination.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_machinedefination.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_machinedefination.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_machinedefination.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_machinedefination.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_machinedefination.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_machinedefination.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_machinedefination.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_machinedefination.Image = (System.Drawing.Image)resources.GetObject("btn_machinedefination.Image");
		this.btn_machinedefination.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_machinedefination.Location = new System.Drawing.Point(12, 158);
		this.btn_machinedefination.Name = "btn_machinedefination";
		this.btn_machinedefination.Size = new System.Drawing.Size(280, 75);
		this.btn_machinedefination.TabIndex = 589;
		this.btn_machinedefination.Text = "Machine Defination";
		this.btn_machinedefination.UseMnemonic = false;
		this.btn_cameracalibration.BackColor = System.Drawing.Color.Transparent;
		this.btn_cameracalibration.ButtonCopy = false;
		this.btn_cameracalibration.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_cameracalibration.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_cameracalibration.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_cameracalibration.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_cameracalibration.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_cameracalibration.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_cameracalibration.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_cameracalibration.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_cameracalibration.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_cameracalibration.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_cameracalibration.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_cameracalibration.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_cameracalibration.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_cameracalibration.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_cameracalibration.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_cameracalibration.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_cameracalibration.Image = (System.Drawing.Image)resources.GetObject("btn_cameracalibration.Image");
		this.btn_cameracalibration.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_cameracalibration.Location = new System.Drawing.Point(12, 440);
		this.btn_cameracalibration.Name = "btn_cameracalibration";
		this.btn_cameracalibration.Size = new System.Drawing.Size(280, 75);
		this.btn_cameracalibration.TabIndex = 588;
		this.btn_cameracalibration.Text = "Camere Calibration";
		this.btn_cameracalibration.UseMnemonic = false;
		this.btn_axesgain.BackColor = System.Drawing.Color.Transparent;
		this.btn_axesgain.ButtonCopy = false;
		this.btn_axesgain.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_axesgain.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_axesgain.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_axesgain.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_axesgain.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_axesgain.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_axesgain.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_axesgain.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_axesgain.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_axesgain.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_axesgain.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_axesgain.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_axesgain.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_axesgain.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_axesgain.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_axesgain.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_axesgain.Image = (System.Drawing.Image)resources.GetObject("btn_axesgain.Image");
		this.btn_axesgain.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_axesgain.Location = new System.Drawing.Point(305, 440);
		this.btn_axesgain.Name = "btn_axesgain";
		this.btn_axesgain.Size = new System.Drawing.Size(280, 75);
		this.btn_axesgain.TabIndex = 587;
		this.btn_axesgain.Text = "Axes Gain";
		this.btn_axesgain.UseMnemonic = false;
		this.btn_camerasettings.BackColor = System.Drawing.Color.Transparent;
		this.btn_camerasettings.ButtonCopy = false;
		this.btn_camerasettings.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_camerasettings.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_camerasettings.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_camerasettings.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_camerasettings.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_camerasettings.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_camerasettings.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_camerasettings.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_camerasettings.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_camerasettings.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_camerasettings.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_camerasettings.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_camerasettings.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_camerasettings.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_camerasettings.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_camerasettings.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_camerasettings.Image = (System.Drawing.Image)resources.GetObject("btn_camerasettings.Image");
		this.btn_camerasettings.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_camerasettings.Location = new System.Drawing.Point(604, 440);
		this.btn_camerasettings.Name = "btn_camerasettings";
		this.btn_camerasettings.Size = new System.Drawing.Size(280, 75);
		this.btn_camerasettings.TabIndex = 586;
		this.btn_camerasettings.Text = "Camera Settings";
		this.btn_camerasettings.UseMnemonic = false;
		this.btn_vagoonsettings.BackColor = System.Drawing.Color.Transparent;
		this.btn_vagoonsettings.ButtonCopy = false;
		this.btn_vagoonsettings.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_vagoonsettings.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_vagoonsettings.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_vagoonsettings.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_vagoonsettings.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_vagoonsettings.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_vagoonsettings.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_vagoonsettings.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_vagoonsettings.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_vagoonsettings.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_vagoonsettings.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_vagoonsettings.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_vagoonsettings.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_vagoonsettings.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_vagoonsettings.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_vagoonsettings.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_vagoonsettings.Image = (System.Drawing.Image)resources.GetObject("btn_vagoonsettings.Image");
		this.btn_vagoonsettings.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_vagoonsettings.Location = new System.Drawing.Point(305, 253);
		this.btn_vagoonsettings.Name = "btn_vagoonsettings";
		this.btn_vagoonsettings.Size = new System.Drawing.Size(280, 75);
		this.btn_vagoonsettings.TabIndex = 585;
		this.btn_vagoonsettings.Text = "Vagon Settings";
		this.btn_vagoonsettings.UseMnemonic = false;
		this.btn_toolsettings.BackColor = System.Drawing.Color.Transparent;
		this.btn_toolsettings.ButtonCopy = false;
		this.btn_toolsettings.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_toolsettings.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_toolsettings.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_toolsettings.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_toolsettings.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_toolsettings.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_toolsettings.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_toolsettings.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_toolsettings.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_toolsettings.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_toolsettings.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_toolsettings.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_toolsettings.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_toolsettings.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_toolsettings.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_toolsettings.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_toolsettings.Image = (System.Drawing.Image)resources.GetObject("btn_toolsettings.Image");
		this.btn_toolsettings.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_toolsettings.Location = new System.Drawing.Point(604, 64);
		this.btn_toolsettings.Name = "btn_toolsettings";
		this.btn_toolsettings.Size = new System.Drawing.Size(280, 75);
		this.btn_toolsettings.TabIndex = 584;
		this.btn_toolsettings.Text = "Machine Settings";
		this.btn_toolsettings.UseMnemonic = false;
		this.btn_calibration.BackColor = System.Drawing.Color.Transparent;
		this.btn_calibration.ButtonCopy = false;
		this.btn_calibration.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_calibration.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_calibration.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_calibration.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_calibration.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_calibration.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_calibration.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_calibration.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_calibration.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_calibration.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_calibration.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_calibration.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_calibration.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_calibration.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_calibration.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_calibration.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_calibration.Image = (System.Drawing.Image)resources.GetObject("btn_calibration.Image");
		this.btn_calibration.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_calibration.Location = new System.Drawing.Point(604, 158);
		this.btn_calibration.Name = "btn_calibration";
		this.btn_calibration.Size = new System.Drawing.Size(280, 75);
		this.btn_calibration.TabIndex = 583;
		this.btn_calibration.Text = "Calibration";
		this.btn_calibration.UseMnemonic = false;
		this.btn_servoconnection.BackColor = System.Drawing.Color.Transparent;
		this.btn_servoconnection.ButtonCopy = false;
		this.btn_servoconnection.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_servoconnection.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_servoconnection.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_servoconnection.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_servoconnection.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_servoconnection.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_servoconnection.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_servoconnection.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_servoconnection.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_servoconnection.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_servoconnection.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_servoconnection.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_servoconnection.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_servoconnection.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_servoconnection.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_servoconnection.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_servoconnection.Image = (System.Drawing.Image)resources.GetObject("btn_servoconnection.Image");
		this.btn_servoconnection.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_servoconnection.Location = new System.Drawing.Point(305, 347);
		this.btn_servoconnection.Name = "btn_servoconnection";
		this.btn_servoconnection.Size = new System.Drawing.Size(280, 75);
		this.btn_servoconnection.TabIndex = 582;
		this.btn_servoconnection.Text = "Servo Connection";
		this.btn_servoconnection.UseMnemonic = false;
		this.btn_millingsettings.BackColor = System.Drawing.Color.Transparent;
		this.btn_millingsettings.ButtonCopy = false;
		this.btn_millingsettings.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_millingsettings.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_millingsettings.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_millingsettings.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_millingsettings.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_millingsettings.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_millingsettings.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_millingsettings.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_millingsettings.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_millingsettings.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_millingsettings.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_millingsettings.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_millingsettings.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_millingsettings.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_millingsettings.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_millingsettings.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_millingsettings.Image = (System.Drawing.Image)resources.GetObject("btn_millingsettings.Image");
		this.btn_millingsettings.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_millingsettings.Location = new System.Drawing.Point(12, 535);
		this.btn_millingsettings.Name = "btn_millingsettings";
		this.btn_millingsettings.Size = new System.Drawing.Size(280, 75);
		this.btn_millingsettings.TabIndex = 581;
		this.btn_millingsettings.Text = "Milling Settings";
		this.btn_millingsettings.UseMnemonic = false;
		this.btn_marblecamsettings.BackColor = System.Drawing.Color.Transparent;
		this.btn_marblecamsettings.ButtonCopy = false;
		this.btn_marblecamsettings.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_marblecamsettings.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_marblecamsettings.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_marblecamsettings.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_marblecamsettings.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_marblecamsettings.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_marblecamsettings.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_marblecamsettings.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_marblecamsettings.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_marblecamsettings.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_marblecamsettings.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_marblecamsettings.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_marblecamsettings.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_marblecamsettings.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_marblecamsettings.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_marblecamsettings.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_marblecamsettings.Image = (System.Drawing.Image)resources.GetObject("btn_marblecamsettings.Image");
		this.btn_marblecamsettings.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_marblecamsettings.Location = new System.Drawing.Point(304, 64);
		this.btn_marblecamsettings.Name = "btn_marblecamsettings";
		this.btn_marblecamsettings.Size = new System.Drawing.Size(280, 75);
		this.btn_marblecamsettings.TabIndex = 579;
		this.btn_marblecamsettings.Text = "Marble Cam Settings";
		this.btn_marblecamsettings.UseMnemonic = false;
		this.btn_AbsoluteHomeSet.ButtonCopy = false;
		this.btn_AbsoluteHomeSet.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_AbsoluteHomeSet.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_AbsoluteHomeSet.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_AbsoluteHomeSet.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_AbsoluteHomeSet.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_AbsoluteHomeSet.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_AbsoluteHomeSet.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_AbsoluteHomeSet.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_AbsoluteHomeSet.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_AbsoluteHomeSet.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_AbsoluteHomeSet.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_AbsoluteHomeSet.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_AbsoluteHomeSet.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_AbsoluteHomeSet.Image = (System.Drawing.Image)resources.GetObject("btn_AbsoluteHomeSet.Image");
		this.btn_AbsoluteHomeSet.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_AbsoluteHomeSet.Location = new System.Drawing.Point(12, 253);
		this.btn_AbsoluteHomeSet.Name = "btn_AbsoluteHomeSet";
		this.btn_AbsoluteHomeSet.Size = new System.Drawing.Size(280, 75);
		this.btn_AbsoluteHomeSet.TabIndex = 573;
		this.btn_AbsoluteHomeSet.Text = "Eksen Sıfırlama";
		this.btn_AbsoluteHomeSet.UseMnemonic = false;
		this.btn_G54Offset.ButtonCopy = false;
		this.btn_G54Offset.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_G54Offset.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_G54Offset.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_G54Offset.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_G54Offset.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_G54Offset.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_G54Offset.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_G54Offset.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_G54Offset.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_G54Offset.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_G54Offset.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_G54Offset.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_G54Offset.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_G54Offset.Image = (System.Drawing.Image)resources.GetObject("btn_G54Offset.Image");
		this.btn_G54Offset.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_G54Offset.Location = new System.Drawing.Point(604, 347);
		this.btn_G54Offset.Name = "btn_G54Offset";
		this.btn_G54Offset.Size = new System.Drawing.Size(280, 75);
		this.btn_G54Offset.TabIndex = 572;
		this.btn_G54Offset.Text = "G54 Offsetleri";
		this.btn_G54Offset.UseMnemonic = false;
		this.btn_GantryPage.BackColor = System.Drawing.Color.Transparent;
		this.btn_GantryPage.ButtonCopy = false;
		this.btn_GantryPage.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_GantryPage.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_GantryPage.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_GantryPage.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_GantryPage.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_GantryPage.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_GantryPage.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_GantryPage.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_GantryPage.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_GantryPage.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_GantryPage.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_GantryPage.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_GantryPage.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_GantryPage.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_GantryPage.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_GantryPage.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_GantryPage.Image = (System.Drawing.Image)resources.GetObject("btn_GantryPage.Image");
		this.btn_GantryPage.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_GantryPage.Location = new System.Drawing.Point(12, 347);
		this.btn_GantryPage.Name = "btn_GantryPage";
		this.btn_GantryPage.Size = new System.Drawing.Size(280, 75);
		this.btn_GantryPage.TabIndex = 570;
		this.btn_GantryPage.Text = "Gantry Ayarı";
		this.btn_GantryPage.UseMnemonic = false;
		this.btn_settingsaxes.BackColor = System.Drawing.Color.Transparent;
		this.btn_settingsaxes.ButtonCopy = false;
		this.btn_settingsaxes.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_settingsaxes.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_settingsaxes.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_settingsaxes.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_settingsaxes.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_settingsaxes.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_settingsaxes.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_settingsaxes.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_settingsaxes.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_settingsaxes.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_settingsaxes.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_settingsaxes.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_settingsaxes.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_settingsaxes.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_settingsaxes.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_settingsaxes.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_settingsaxes.Image = (System.Drawing.Image)resources.GetObject("btn_settingsaxes.Image");
		this.btn_settingsaxes.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_settingsaxes.Location = new System.Drawing.Point(12, 64);
		this.btn_settingsaxes.Name = "btn_settingsaxes";
		this.btn_settingsaxes.Size = new System.Drawing.Size(280, 75);
		this.btn_settingsaxes.TabIndex = 566;
		this.btn_settingsaxes.Text = "Axes/CNC Settings";
		this.btn_settingsaxes.UseMnemonic = false;
		this.btn_kinematic.ButtonCopy = false;
		this.btn_kinematic.ButtonDownDisplay.BackColor = System.Drawing.Color.DimGray;
		this.btn_kinematic.ButtonOverDisplay.BackColor = System.Drawing.Color.Gray;
		this.btn_kinematic.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_kinematic.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_kinematic.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_kinematic.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_kinematic.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_kinematic.Image = (System.Drawing.Image)resources.GetObject("btn_kinematic.Image");
		this.btn_kinematic.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_kinematic.Location = new System.Drawing.Point(604, 253);
		this.btn_kinematic.Name = "btn_kinematic";
		this.btn_kinematic.Size = new System.Drawing.Size(280, 75);
		this.btn_kinematic.TabIndex = 70;
		this.btn_kinematic.Text = "Kinematic Settings";
		this.btn_kinematic.UseMnemonic = false;
		this.btn_circularspeedreduce.BackColor = System.Drawing.Color.Transparent;
		this.btn_circularspeedreduce.ButtonCopy = false;
		this.btn_circularspeedreduce.ButtonDownDisplay.BackColor = System.Drawing.Color.Gold;
		this.btn_circularspeedreduce.ButtonDownDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_circularspeedreduce.ButtonDownDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_circularspeedreduce.ButtonDownDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circularspeedreduce.ButtonOverDisplay.BackColor = System.Drawing.Color.Gainsboro;
		this.btn_circularspeedreduce.ButtonOverDisplay.Border.Color = System.Drawing.Color.Black;
		this.btn_circularspeedreduce.ButtonOverDisplay.Fonts.Font = new System.Drawing.Font("Arial", 11.25f, System.Drawing.FontStyle.Bold);
		this.btn_circularspeedreduce.ButtonOverDisplay.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circularspeedreduce.ControlStyle = buControls.Controls.ControlStyle.Menu4;
		this.btn_circularspeedreduce.Display.BackColor = System.Drawing.Color.PeachPuff;
		this.btn_circularspeedreduce.Display.Border.Color = System.Drawing.Color.Black;
		this.btn_circularspeedreduce.Display.Fonts.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 162);
		this.btn_circularspeedreduce.Display.Fonts.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circularspeedreduce.Font = new System.Drawing.Font("Microsoft Sans Serif", 10f);
		this.btn_circularspeedreduce.ForeColor = System.Drawing.Color.FromArgb(0, 27, 72);
		this.btn_circularspeedreduce.Geometry.ShapeMode = buControls.Controls.ShapeType.Arc;
		this.btn_circularspeedreduce.Image = (System.Drawing.Image)resources.GetObject("btn_circularspeedreduce.Image");
		this.btn_circularspeedreduce.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
		this.btn_circularspeedreduce.Location = new System.Drawing.Point(604, 535);
		this.btn_circularspeedreduce.Name = "btn_circularspeedreduce";
		this.btn_circularspeedreduce.Size = new System.Drawing.Size(280, 75);
		this.btn_circularspeedreduce.TabIndex = 593;
		this.btn_circularspeedreduce.Text = "Circular Speed Reduction";
		this.btn_circularspeedreduce.UseMnemonic = false;
		base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
		base.ClientSize = new System.Drawing.Size(892, 628);
		base.Controls.Add(this.buGround1);
		base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
		base.Name = "F_MenuSettings";
		this.Text = "Menu";
		this.buGround1.ResumeLayout(false);
		base.ResumeLayout(false);
	}
}
