<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SharpGLTF.Toolkit</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Text.Json">
      <HintPath>..\..\System.Text.Json.dll</HintPath>
    </Reference>
    <Reference Include="SharpGLTF.Core">
      <HintPath>..\..\SharpGLTF.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics.Vectors">
      <HintPath>..\..\System.Numerics.Vectors.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\..\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="SharpGLTF.Runtime">
      <HintPath>..\..\SharpGLTF.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>