using System;
using Xbim.Ifc2x3.MeasureResource;
using Xbim.Ifc4.DateTimeResource;
using Xbim.Ifc4.MeasureResource;

namespace Xbim.Ifc4.Interfaces;

public static class IfcValueHelper
{
	public static IIfcValue ToIfc4(this Xbim.Ifc2x3.MeasureResource.IfcValue member)
	{
		if (member == null)
		{
			return null;
		}
		return member.GetType().Name switch
		{
			"IfcVolumeMeasure" => new Xbim.Ifc4.MeasureResource.IfcVolumeMeasure((Xbim.Ifc2x3.MeasureResource.IfcVolumeMeasure)(object)member), 
			"IfcTimeMeasure" => new Xbim.Ifc4.MeasureResource.IfcTimeMeasure((Xbim.Ifc2x3.MeasureResource.IfcTimeMeasure)(object)member), 
			"IfcThermodynamicTemperatureMeasure" => new Xbim.Ifc4.MeasureResource.IfcThermodynamicTemperatureMeasure((Xbim.Ifc2x3.MeasureResource.IfcThermodynamicTemperatureMeasure)(object)member), 
			"IfcSolidAngleMeasure" => new Xbim.Ifc4.MeasureResource.IfcSolidAngleMeasure((Xbim.Ifc2x3.MeasureResource.IfcSolidAngleMeasure)(object)member), 
			"IfcPositiveRatioMeasure" => new Xbim.Ifc4.MeasureResource.IfcPositiveRatioMeasure((Xbim.Ifc2x3.MeasureResource.IfcPositiveRatioMeasure)(object)member), 
			"IfcRatioMeasure" => new Xbim.Ifc4.MeasureResource.IfcRatioMeasure((Xbim.Ifc2x3.MeasureResource.IfcRatioMeasure)(object)member), 
			"IfcPositivePlaneAngleMeasure" => new Xbim.Ifc4.MeasureResource.IfcPositivePlaneAngleMeasure((Xbim.Ifc2x3.MeasureResource.IfcPositivePlaneAngleMeasure)(object)member), 
			"IfcPlaneAngleMeasure" => new Xbim.Ifc4.MeasureResource.IfcPlaneAngleMeasure((Xbim.Ifc2x3.MeasureResource.IfcPlaneAngleMeasure)(object)member), 
			"IfcParameterValue" => new Xbim.Ifc4.MeasureResource.IfcParameterValue((Xbim.Ifc2x3.MeasureResource.IfcParameterValue)(object)member), 
			"IfcNumericMeasure" => new Xbim.Ifc4.MeasureResource.IfcNumericMeasure((Xbim.Ifc2x3.MeasureResource.IfcNumericMeasure)(object)member), 
			"IfcMassMeasure" => new Xbim.Ifc4.MeasureResource.IfcMassMeasure((Xbim.Ifc2x3.MeasureResource.IfcMassMeasure)(object)member), 
			"IfcPositiveLengthMeasure" => new Xbim.Ifc4.MeasureResource.IfcPositiveLengthMeasure((Xbim.Ifc2x3.MeasureResource.IfcPositiveLengthMeasure)(object)member), 
			"IfcLengthMeasure" => new Xbim.Ifc4.MeasureResource.IfcLengthMeasure((Xbim.Ifc2x3.MeasureResource.IfcLengthMeasure)(object)member), 
			"IfcElectricCurrentMeasure" => new Xbim.Ifc4.MeasureResource.IfcElectricCurrentMeasure((Xbim.Ifc2x3.MeasureResource.IfcElectricCurrentMeasure)(object)member), 
			"IfcDescriptiveMeasure" => new Xbim.Ifc4.MeasureResource.IfcDescriptiveMeasure((Xbim.Ifc2x3.MeasureResource.IfcDescriptiveMeasure)(object)member), 
			"IfcCountMeasure" => new Xbim.Ifc4.MeasureResource.IfcCountMeasure((Xbim.Ifc2x3.MeasureResource.IfcCountMeasure)(object)member), 
			"IfcContextDependentMeasure" => new Xbim.Ifc4.MeasureResource.IfcContextDependentMeasure((Xbim.Ifc2x3.MeasureResource.IfcContextDependentMeasure)(object)member), 
			"IfcAreaMeasure" => new Xbim.Ifc4.MeasureResource.IfcAreaMeasure((Xbim.Ifc2x3.MeasureResource.IfcAreaMeasure)(object)member), 
			"IfcAmountOfSubstanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcAmountOfSubstanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcAmountOfSubstanceMeasure)(object)member), 
			"IfcLuminousIntensityMeasure" => new Xbim.Ifc4.MeasureResource.IfcLuminousIntensityMeasure((Xbim.Ifc2x3.MeasureResource.IfcLuminousIntensityMeasure)(object)member), 
			"IfcNormalisedRatioMeasure" => new Xbim.Ifc4.MeasureResource.IfcNormalisedRatioMeasure((Xbim.Ifc2x3.MeasureResource.IfcNormalisedRatioMeasure)(object)member), 
			"IfcComplexNumber" => new Xbim.Ifc4.MeasureResource.IfcComplexNumber((Xbim.Ifc2x3.MeasureResource.IfcComplexNumber)(object)member), 
			"IfcInteger" => new Xbim.Ifc4.MeasureResource.IfcInteger((Xbim.Ifc2x3.MeasureResource.IfcInteger)(object)member), 
			"IfcReal" => new Xbim.Ifc4.MeasureResource.IfcReal((Xbim.Ifc2x3.MeasureResource.IfcReal)(object)member), 
			"IfcBoolean" => new Xbim.Ifc4.MeasureResource.IfcBoolean((Xbim.Ifc2x3.MeasureResource.IfcBoolean)(object)member), 
			"IfcIdentifier" => new Xbim.Ifc4.MeasureResource.IfcIdentifier((Xbim.Ifc2x3.MeasureResource.IfcIdentifier)(object)member), 
			"IfcText" => new Xbim.Ifc4.MeasureResource.IfcText((Xbim.Ifc2x3.MeasureResource.IfcText)(object)member), 
			"IfcLabel" => new Xbim.Ifc4.MeasureResource.IfcLabel((Xbim.Ifc2x3.MeasureResource.IfcLabel)(object)member), 
			"IfcLogical" => new Xbim.Ifc4.MeasureResource.IfcLogical((Xbim.Ifc2x3.MeasureResource.IfcLogical)(object)member), 
			"IfcVolumetricFlowRateMeasure" => new Xbim.Ifc4.MeasureResource.IfcVolumetricFlowRateMeasure((Xbim.Ifc2x3.MeasureResource.IfcVolumetricFlowRateMeasure)(object)member), 
			"IfcTimeStamp" => new Xbim.Ifc4.DateTimeResource.IfcTimeStamp((Xbim.Ifc2x3.MeasureResource.IfcTimeStamp)(object)member), 
			"IfcThermalTransmittanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcThermalTransmittanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcThermalTransmittanceMeasure)(object)member), 
			"IfcThermalResistanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcThermalResistanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcThermalResistanceMeasure)(object)member), 
			"IfcThermalAdmittanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcThermalAdmittanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcThermalAdmittanceMeasure)(object)member), 
			"IfcPressureMeasure" => new Xbim.Ifc4.MeasureResource.IfcPressureMeasure((Xbim.Ifc2x3.MeasureResource.IfcPressureMeasure)(object)member), 
			"IfcPowerMeasure" => new Xbim.Ifc4.MeasureResource.IfcPowerMeasure((Xbim.Ifc2x3.MeasureResource.IfcPowerMeasure)(object)member), 
			"IfcMassFlowRateMeasure" => new Xbim.Ifc4.MeasureResource.IfcMassFlowRateMeasure((Xbim.Ifc2x3.MeasureResource.IfcMassFlowRateMeasure)(object)member), 
			"IfcMassDensityMeasure" => new Xbim.Ifc4.MeasureResource.IfcMassDensityMeasure((Xbim.Ifc2x3.MeasureResource.IfcMassDensityMeasure)(object)member), 
			"IfcLinearVelocityMeasure" => new Xbim.Ifc4.MeasureResource.IfcLinearVelocityMeasure((Xbim.Ifc2x3.MeasureResource.IfcLinearVelocityMeasure)(object)member), 
			"IfcKinematicViscosityMeasure" => new Xbim.Ifc4.MeasureResource.IfcKinematicViscosityMeasure((Xbim.Ifc2x3.MeasureResource.IfcKinematicViscosityMeasure)(object)member), 
			"IfcIntegerCountRateMeasure" => new Xbim.Ifc4.MeasureResource.IfcIntegerCountRateMeasure((Xbim.Ifc2x3.MeasureResource.IfcIntegerCountRateMeasure)(object)member), 
			"IfcHeatFluxDensityMeasure" => new Xbim.Ifc4.MeasureResource.IfcHeatFluxDensityMeasure((Xbim.Ifc2x3.MeasureResource.IfcHeatFluxDensityMeasure)(object)member), 
			"IfcFrequencyMeasure" => new Xbim.Ifc4.MeasureResource.IfcFrequencyMeasure((Xbim.Ifc2x3.MeasureResource.IfcFrequencyMeasure)(object)member), 
			"IfcEnergyMeasure" => new Xbim.Ifc4.MeasureResource.IfcEnergyMeasure((Xbim.Ifc2x3.MeasureResource.IfcEnergyMeasure)(object)member), 
			"IfcElectricVoltageMeasure" => new Xbim.Ifc4.MeasureResource.IfcElectricVoltageMeasure((Xbim.Ifc2x3.MeasureResource.IfcElectricVoltageMeasure)(object)member), 
			"IfcDynamicViscosityMeasure" => new Xbim.Ifc4.MeasureResource.IfcDynamicViscosityMeasure((Xbim.Ifc2x3.MeasureResource.IfcDynamicViscosityMeasure)(object)member), 
			"IfcCompoundPlaneAngleMeasure" => new Xbim.Ifc4.MeasureResource.IfcCompoundPlaneAngleMeasure((Xbim.Ifc2x3.MeasureResource.IfcCompoundPlaneAngleMeasure)(object)member), 
			"IfcAngularVelocityMeasure" => new Xbim.Ifc4.MeasureResource.IfcAngularVelocityMeasure((Xbim.Ifc2x3.MeasureResource.IfcAngularVelocityMeasure)(object)member), 
			"IfcThermalConductivityMeasure" => new Xbim.Ifc4.MeasureResource.IfcThermalConductivityMeasure((Xbim.Ifc2x3.MeasureResource.IfcThermalConductivityMeasure)(object)member), 
			"IfcMolecularWeightMeasure" => new Xbim.Ifc4.MeasureResource.IfcMolecularWeightMeasure((Xbim.Ifc2x3.MeasureResource.IfcMolecularWeightMeasure)(object)member), 
			"IfcVaporPermeabilityMeasure" => new Xbim.Ifc4.MeasureResource.IfcVaporPermeabilityMeasure((Xbim.Ifc2x3.MeasureResource.IfcVaporPermeabilityMeasure)(object)member), 
			"IfcMoistureDiffusivityMeasure" => new Xbim.Ifc4.MeasureResource.IfcMoistureDiffusivityMeasure((Xbim.Ifc2x3.MeasureResource.IfcMoistureDiffusivityMeasure)(object)member), 
			"IfcIsothermalMoistureCapacityMeasure" => new Xbim.Ifc4.MeasureResource.IfcIsothermalMoistureCapacityMeasure((Xbim.Ifc2x3.MeasureResource.IfcIsothermalMoistureCapacityMeasure)(object)member), 
			"IfcSpecificHeatCapacityMeasure" => new Xbim.Ifc4.MeasureResource.IfcSpecificHeatCapacityMeasure((Xbim.Ifc2x3.MeasureResource.IfcSpecificHeatCapacityMeasure)(object)member), 
			"IfcMonetaryMeasure" => new Xbim.Ifc4.MeasureResource.IfcMonetaryMeasure((Xbim.Ifc2x3.MeasureResource.IfcMonetaryMeasure)(object)member), 
			"IfcMagneticFluxDensityMeasure" => new Xbim.Ifc4.MeasureResource.IfcMagneticFluxDensityMeasure((Xbim.Ifc2x3.MeasureResource.IfcMagneticFluxDensityMeasure)(object)member), 
			"IfcMagneticFluxMeasure" => new Xbim.Ifc4.MeasureResource.IfcMagneticFluxMeasure((Xbim.Ifc2x3.MeasureResource.IfcMagneticFluxMeasure)(object)member), 
			"IfcLuminousFluxMeasure" => new Xbim.Ifc4.MeasureResource.IfcLuminousFluxMeasure((Xbim.Ifc2x3.MeasureResource.IfcLuminousFluxMeasure)(object)member), 
			"IfcForceMeasure" => new Xbim.Ifc4.MeasureResource.IfcForceMeasure((Xbim.Ifc2x3.MeasureResource.IfcForceMeasure)(object)member), 
			"IfcInductanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcInductanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcInductanceMeasure)(object)member), 
			"IfcIlluminanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcIlluminanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcIlluminanceMeasure)(object)member), 
			"IfcElectricResistanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcElectricResistanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcElectricResistanceMeasure)(object)member), 
			"IfcElectricConductanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcElectricConductanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcElectricConductanceMeasure)(object)member), 
			"IfcElectricChargeMeasure" => new Xbim.Ifc4.MeasureResource.IfcElectricChargeMeasure((Xbim.Ifc2x3.MeasureResource.IfcElectricChargeMeasure)(object)member), 
			"IfcDoseEquivalentMeasure" => new Xbim.Ifc4.MeasureResource.IfcDoseEquivalentMeasure((Xbim.Ifc2x3.MeasureResource.IfcDoseEquivalentMeasure)(object)member), 
			"IfcElectricCapacitanceMeasure" => new Xbim.Ifc4.MeasureResource.IfcElectricCapacitanceMeasure((Xbim.Ifc2x3.MeasureResource.IfcElectricCapacitanceMeasure)(object)member), 
			"IfcAbsorbedDoseMeasure" => new Xbim.Ifc4.MeasureResource.IfcAbsorbedDoseMeasure((Xbim.Ifc2x3.MeasureResource.IfcAbsorbedDoseMeasure)(object)member), 
			"IfcRadioActivityMeasure" => new Xbim.Ifc4.MeasureResource.IfcRadioActivityMeasure((Xbim.Ifc2x3.MeasureResource.IfcRadioActivityMeasure)(object)member), 
			"IfcRotationalFrequencyMeasure" => new Xbim.Ifc4.MeasureResource.IfcRotationalFrequencyMeasure((Xbim.Ifc2x3.MeasureResource.IfcRotationalFrequencyMeasure)(object)member), 
			"IfcTorqueMeasure" => new Xbim.Ifc4.MeasureResource.IfcTorqueMeasure((Xbim.Ifc2x3.MeasureResource.IfcTorqueMeasure)(object)member), 
			"IfcAccelerationMeasure" => new Xbim.Ifc4.MeasureResource.IfcAccelerationMeasure((Xbim.Ifc2x3.MeasureResource.IfcAccelerationMeasure)(object)member), 
			"IfcLinearForceMeasure" => new Xbim.Ifc4.MeasureResource.IfcLinearForceMeasure((Xbim.Ifc2x3.MeasureResource.IfcLinearForceMeasure)(object)member), 
			"IfcLinearStiffnessMeasure" => new Xbim.Ifc4.MeasureResource.IfcLinearStiffnessMeasure((Xbim.Ifc2x3.MeasureResource.IfcLinearStiffnessMeasure)(object)member), 
			"IfcModulusOfSubgradeReactionMeasure" => new Xbim.Ifc4.MeasureResource.IfcModulusOfSubgradeReactionMeasure((Xbim.Ifc2x3.MeasureResource.IfcModulusOfSubgradeReactionMeasure)(object)member), 
			"IfcModulusOfElasticityMeasure" => new Xbim.Ifc4.MeasureResource.IfcModulusOfElasticityMeasure((Xbim.Ifc2x3.MeasureResource.IfcModulusOfElasticityMeasure)(object)member), 
			"IfcMomentOfInertiaMeasure" => new Xbim.Ifc4.MeasureResource.IfcMomentOfInertiaMeasure((Xbim.Ifc2x3.MeasureResource.IfcMomentOfInertiaMeasure)(object)member), 
			"IfcPlanarForceMeasure" => new Xbim.Ifc4.MeasureResource.IfcPlanarForceMeasure((Xbim.Ifc2x3.MeasureResource.IfcPlanarForceMeasure)(object)member), 
			"IfcRotationalStiffnessMeasure" => new Xbim.Ifc4.MeasureResource.IfcRotationalStiffnessMeasure((Xbim.Ifc2x3.MeasureResource.IfcRotationalStiffnessMeasure)(object)member), 
			"IfcShearModulusMeasure" => new Xbim.Ifc4.MeasureResource.IfcShearModulusMeasure((Xbim.Ifc2x3.MeasureResource.IfcShearModulusMeasure)(object)member), 
			"IfcLinearMomentMeasure" => new Xbim.Ifc4.MeasureResource.IfcLinearMomentMeasure((Xbim.Ifc2x3.MeasureResource.IfcLinearMomentMeasure)(object)member), 
			"IfcLuminousIntensityDistributionMeasure" => new Xbim.Ifc4.MeasureResource.IfcLuminousIntensityDistributionMeasure((Xbim.Ifc2x3.MeasureResource.IfcLuminousIntensityDistributionMeasure)(object)member), 
			"IfcCurvatureMeasure" => new Xbim.Ifc4.MeasureResource.IfcCurvatureMeasure((Xbim.Ifc2x3.MeasureResource.IfcCurvatureMeasure)(object)member), 
			"IfcMassPerLengthMeasure" => new Xbim.Ifc4.MeasureResource.IfcMassPerLengthMeasure((Xbim.Ifc2x3.MeasureResource.IfcMassPerLengthMeasure)(object)member), 
			"IfcModulusOfLinearSubgradeReactionMeasure" => new Xbim.Ifc4.MeasureResource.IfcModulusOfLinearSubgradeReactionMeasure((Xbim.Ifc2x3.MeasureResource.IfcModulusOfLinearSubgradeReactionMeasure)(object)member), 
			"IfcModulusOfRotationalSubgradeReactionMeasure" => new Xbim.Ifc4.MeasureResource.IfcModulusOfRotationalSubgradeReactionMeasure((Xbim.Ifc2x3.MeasureResource.IfcModulusOfRotationalSubgradeReactionMeasure)(object)member), 
			"IfcRotationalMassMeasure" => new Xbim.Ifc4.MeasureResource.IfcRotationalMassMeasure((Xbim.Ifc2x3.MeasureResource.IfcRotationalMassMeasure)(object)member), 
			"IfcSectionalAreaIntegralMeasure" => new Xbim.Ifc4.MeasureResource.IfcSectionalAreaIntegralMeasure((Xbim.Ifc2x3.MeasureResource.IfcSectionalAreaIntegralMeasure)(object)member), 
			"IfcSectionModulusMeasure" => new Xbim.Ifc4.MeasureResource.IfcSectionModulusMeasure((Xbim.Ifc2x3.MeasureResource.IfcSectionModulusMeasure)(object)member), 
			"IfcTemperatureGradientMeasure" => new Xbim.Ifc4.MeasureResource.IfcTemperatureGradientMeasure((Xbim.Ifc2x3.MeasureResource.IfcTemperatureGradientMeasure)(object)member), 
			"IfcThermalExpansionCoefficientMeasure" => new Xbim.Ifc4.MeasureResource.IfcThermalExpansionCoefficientMeasure((Xbim.Ifc2x3.MeasureResource.IfcThermalExpansionCoefficientMeasure)(object)member), 
			"IfcWarpingConstantMeasure" => new Xbim.Ifc4.MeasureResource.IfcWarpingConstantMeasure((Xbim.Ifc2x3.MeasureResource.IfcWarpingConstantMeasure)(object)member), 
			"IfcWarpingMomentMeasure" => new Xbim.Ifc4.MeasureResource.IfcWarpingMomentMeasure((Xbim.Ifc2x3.MeasureResource.IfcWarpingMomentMeasure)(object)member), 
			"IfcSoundPowerMeasure" => new Xbim.Ifc4.MeasureResource.IfcSoundPowerMeasure((Xbim.Ifc2x3.MeasureResource.IfcSoundPowerMeasure)(object)member), 
			"IfcSoundPressureMeasure" => new Xbim.Ifc4.MeasureResource.IfcSoundPressureMeasure((Xbim.Ifc2x3.MeasureResource.IfcSoundPressureMeasure)(object)member), 
			"IfcHeatingValueMeasure" => new Xbim.Ifc4.MeasureResource.IfcHeatingValueMeasure((Xbim.Ifc2x3.MeasureResource.IfcHeatingValueMeasure)(object)member), 
			"IfcPHMeasure" => new Xbim.Ifc4.MeasureResource.IfcPHMeasure((Xbim.Ifc2x3.MeasureResource.IfcPHMeasure)(object)member), 
			"IfcIonConcentrationMeasure" => new Xbim.Ifc4.MeasureResource.IfcIonConcentrationMeasure((Xbim.Ifc2x3.MeasureResource.IfcIonConcentrationMeasure)(object)member), 
			_ => throw new NotSupportedException(), 
		};
	}

	public static Xbim.Ifc2x3.MeasureResource.IfcValue ToIfc3(this IIfcValue member)
	{
		if (member == null)
		{
			return null;
		}
		return member.GetType().Name switch
		{
			"IfcAbsorbedDoseMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcAbsorbedDoseMeasure((Xbim.Ifc4.MeasureResource.IfcAbsorbedDoseMeasure)(object)member), 
			"IfcAccelerationMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcAccelerationMeasure((Xbim.Ifc4.MeasureResource.IfcAccelerationMeasure)(object)member), 
			"IfcAngularVelocityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcAngularVelocityMeasure((Xbim.Ifc4.MeasureResource.IfcAngularVelocityMeasure)(object)member), 
			"IfcAreaDensityMeasure" => null, 
			"IfcCompoundPlaneAngleMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcCompoundPlaneAngleMeasure((Xbim.Ifc4.MeasureResource.IfcCompoundPlaneAngleMeasure)(object)member), 
			"IfcCurvatureMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcCurvatureMeasure((Xbim.Ifc4.MeasureResource.IfcCurvatureMeasure)(object)member), 
			"IfcDoseEquivalentMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcDoseEquivalentMeasure((Xbim.Ifc4.MeasureResource.IfcDoseEquivalentMeasure)(object)member), 
			"IfcDynamicViscosityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcDynamicViscosityMeasure((Xbim.Ifc4.MeasureResource.IfcDynamicViscosityMeasure)(object)member), 
			"IfcElectricCapacitanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcElectricCapacitanceMeasure((Xbim.Ifc4.MeasureResource.IfcElectricCapacitanceMeasure)(object)member), 
			"IfcElectricChargeMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcElectricChargeMeasure((Xbim.Ifc4.MeasureResource.IfcElectricChargeMeasure)(object)member), 
			"IfcElectricConductanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcElectricConductanceMeasure((Xbim.Ifc4.MeasureResource.IfcElectricConductanceMeasure)(object)member), 
			"IfcElectricResistanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcElectricResistanceMeasure((Xbim.Ifc4.MeasureResource.IfcElectricResistanceMeasure)(object)member), 
			"IfcElectricVoltageMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcElectricVoltageMeasure((Xbim.Ifc4.MeasureResource.IfcElectricVoltageMeasure)(object)member), 
			"IfcEnergyMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcEnergyMeasure((Xbim.Ifc4.MeasureResource.IfcEnergyMeasure)(object)member), 
			"IfcForceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcForceMeasure((Xbim.Ifc4.MeasureResource.IfcForceMeasure)(object)member), 
			"IfcFrequencyMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcFrequencyMeasure((Xbim.Ifc4.MeasureResource.IfcFrequencyMeasure)(object)member), 
			"IfcHeatFluxDensityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcHeatFluxDensityMeasure((Xbim.Ifc4.MeasureResource.IfcHeatFluxDensityMeasure)(object)member), 
			"IfcHeatingValueMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcHeatingValueMeasure((Xbim.Ifc4.MeasureResource.IfcHeatingValueMeasure)(object)member), 
			"IfcIlluminanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcIlluminanceMeasure((Xbim.Ifc4.MeasureResource.IfcIlluminanceMeasure)(object)member), 
			"IfcInductanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcInductanceMeasure((Xbim.Ifc4.MeasureResource.IfcInductanceMeasure)(object)member), 
			"IfcIntegerCountRateMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcIntegerCountRateMeasure((Xbim.Ifc4.MeasureResource.IfcIntegerCountRateMeasure)(object)member), 
			"IfcIonConcentrationMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcIonConcentrationMeasure((Xbim.Ifc4.MeasureResource.IfcIonConcentrationMeasure)(object)member), 
			"IfcIsothermalMoistureCapacityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcIsothermalMoistureCapacityMeasure((Xbim.Ifc4.MeasureResource.IfcIsothermalMoistureCapacityMeasure)(object)member), 
			"IfcKinematicViscosityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcKinematicViscosityMeasure((Xbim.Ifc4.MeasureResource.IfcKinematicViscosityMeasure)(object)member), 
			"IfcLinearForceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLinearForceMeasure((Xbim.Ifc4.MeasureResource.IfcLinearForceMeasure)(object)member), 
			"IfcLinearMomentMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLinearMomentMeasure((Xbim.Ifc4.MeasureResource.IfcLinearMomentMeasure)(object)member), 
			"IfcLinearStiffnessMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLinearStiffnessMeasure((Xbim.Ifc4.MeasureResource.IfcLinearStiffnessMeasure)(object)member), 
			"IfcLinearVelocityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLinearVelocityMeasure((Xbim.Ifc4.MeasureResource.IfcLinearVelocityMeasure)(object)member), 
			"IfcLuminousFluxMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLuminousFluxMeasure((Xbim.Ifc4.MeasureResource.IfcLuminousFluxMeasure)(object)member), 
			"IfcLuminousIntensityDistributionMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLuminousIntensityDistributionMeasure((Xbim.Ifc4.MeasureResource.IfcLuminousIntensityDistributionMeasure)(object)member), 
			"IfcMagneticFluxDensityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMagneticFluxDensityMeasure((Xbim.Ifc4.MeasureResource.IfcMagneticFluxDensityMeasure)(object)member), 
			"IfcMagneticFluxMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMagneticFluxMeasure((Xbim.Ifc4.MeasureResource.IfcMagneticFluxMeasure)(object)member), 
			"IfcMassDensityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMassDensityMeasure((Xbim.Ifc4.MeasureResource.IfcMassDensityMeasure)(object)member), 
			"IfcMassFlowRateMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMassFlowRateMeasure((Xbim.Ifc4.MeasureResource.IfcMassFlowRateMeasure)(object)member), 
			"IfcMassPerLengthMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMassPerLengthMeasure((Xbim.Ifc4.MeasureResource.IfcMassPerLengthMeasure)(object)member), 
			"IfcModulusOfElasticityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcModulusOfElasticityMeasure((Xbim.Ifc4.MeasureResource.IfcModulusOfElasticityMeasure)(object)member), 
			"IfcModulusOfLinearSubgradeReactionMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcModulusOfLinearSubgradeReactionMeasure((Xbim.Ifc4.MeasureResource.IfcModulusOfLinearSubgradeReactionMeasure)(object)member), 
			"IfcModulusOfRotationalSubgradeReactionMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcModulusOfRotationalSubgradeReactionMeasure((Xbim.Ifc4.MeasureResource.IfcModulusOfRotationalSubgradeReactionMeasure)(object)member), 
			"IfcModulusOfSubgradeReactionMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcModulusOfSubgradeReactionMeasure((Xbim.Ifc4.MeasureResource.IfcModulusOfSubgradeReactionMeasure)(object)member), 
			"IfcMoistureDiffusivityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMoistureDiffusivityMeasure((Xbim.Ifc4.MeasureResource.IfcMoistureDiffusivityMeasure)(object)member), 
			"IfcMolecularWeightMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMolecularWeightMeasure((Xbim.Ifc4.MeasureResource.IfcMolecularWeightMeasure)(object)member), 
			"IfcMomentOfInertiaMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMomentOfInertiaMeasure((Xbim.Ifc4.MeasureResource.IfcMomentOfInertiaMeasure)(object)member), 
			"IfcMonetaryMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMonetaryMeasure((Xbim.Ifc4.MeasureResource.IfcMonetaryMeasure)(object)member), 
			"IfcPHMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPHMeasure((Xbim.Ifc4.MeasureResource.IfcPHMeasure)(object)member), 
			"IfcPlanarForceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPlanarForceMeasure((Xbim.Ifc4.MeasureResource.IfcPlanarForceMeasure)(object)member), 
			"IfcPowerMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPowerMeasure((Xbim.Ifc4.MeasureResource.IfcPowerMeasure)(object)member), 
			"IfcPressureMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPressureMeasure((Xbim.Ifc4.MeasureResource.IfcPressureMeasure)(object)member), 
			"IfcRadioActivityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcRadioActivityMeasure((Xbim.Ifc4.MeasureResource.IfcRadioActivityMeasure)(object)member), 
			"IfcRotationalFrequencyMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcRotationalFrequencyMeasure((Xbim.Ifc4.MeasureResource.IfcRotationalFrequencyMeasure)(object)member), 
			"IfcRotationalMassMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcRotationalMassMeasure((Xbim.Ifc4.MeasureResource.IfcRotationalMassMeasure)(object)member), 
			"IfcRotationalStiffnessMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcRotationalStiffnessMeasure((Xbim.Ifc4.MeasureResource.IfcRotationalStiffnessMeasure)(object)member), 
			"IfcSectionModulusMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSectionModulusMeasure((Xbim.Ifc4.MeasureResource.IfcSectionModulusMeasure)(object)member), 
			"IfcSectionalAreaIntegralMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSectionalAreaIntegralMeasure((Xbim.Ifc4.MeasureResource.IfcSectionalAreaIntegralMeasure)(object)member), 
			"IfcShearModulusMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcShearModulusMeasure((Xbim.Ifc4.MeasureResource.IfcShearModulusMeasure)(object)member), 
			"IfcSoundPowerLevelMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSoundPowerMeasure((IfcSoundPowerLevelMeasure)(object)member), 
			"IfcSoundPowerMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSoundPowerMeasure((Xbim.Ifc4.MeasureResource.IfcSoundPowerMeasure)(object)member), 
			"IfcSoundPressureLevelMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSoundPressureMeasure((IfcSoundPressureLevelMeasure)(object)member), 
			"IfcSoundPressureMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSoundPressureMeasure((Xbim.Ifc4.MeasureResource.IfcSoundPressureMeasure)(object)member), 
			"IfcSpecificHeatCapacityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSpecificHeatCapacityMeasure((Xbim.Ifc4.MeasureResource.IfcSpecificHeatCapacityMeasure)(object)member), 
			"IfcTemperatureGradientMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcTemperatureGradientMeasure((Xbim.Ifc4.MeasureResource.IfcTemperatureGradientMeasure)(object)member), 
			"IfcTemperatureRateOfChangeMeasure" => null, 
			"IfcThermalAdmittanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcThermalAdmittanceMeasure((Xbim.Ifc4.MeasureResource.IfcThermalAdmittanceMeasure)(object)member), 
			"IfcThermalConductivityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcThermalConductivityMeasure((Xbim.Ifc4.MeasureResource.IfcThermalConductivityMeasure)(object)member), 
			"IfcThermalExpansionCoefficientMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcThermalExpansionCoefficientMeasure((Xbim.Ifc4.MeasureResource.IfcThermalExpansionCoefficientMeasure)(object)member), 
			"IfcThermalResistanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcThermalResistanceMeasure((Xbim.Ifc4.MeasureResource.IfcThermalResistanceMeasure)(object)member), 
			"IfcThermalTransmittanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcThermalTransmittanceMeasure((Xbim.Ifc4.MeasureResource.IfcThermalTransmittanceMeasure)(object)member), 
			"IfcTorqueMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcTorqueMeasure((Xbim.Ifc4.MeasureResource.IfcTorqueMeasure)(object)member), 
			"IfcVaporPermeabilityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcVaporPermeabilityMeasure((Xbim.Ifc4.MeasureResource.IfcVaporPermeabilityMeasure)(object)member), 
			"IfcVolumetricFlowRateMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcVolumetricFlowRateMeasure((Xbim.Ifc4.MeasureResource.IfcVolumetricFlowRateMeasure)(object)member), 
			"IfcWarpingConstantMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcWarpingConstantMeasure((Xbim.Ifc4.MeasureResource.IfcWarpingConstantMeasure)(object)member), 
			"IfcWarpingMomentMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcWarpingMomentMeasure((Xbim.Ifc4.MeasureResource.IfcWarpingMomentMeasure)(object)member), 
			"IfcAmountOfSubstanceMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcAmountOfSubstanceMeasure((Xbim.Ifc4.MeasureResource.IfcAmountOfSubstanceMeasure)(object)member), 
			"IfcAreaMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcAreaMeasure((Xbim.Ifc4.MeasureResource.IfcAreaMeasure)(object)member), 
			"IfcComplexNumber" => new Xbim.Ifc2x3.MeasureResource.IfcComplexNumber((Xbim.Ifc4.MeasureResource.IfcComplexNumber)(object)member), 
			"IfcContextDependentMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcContextDependentMeasure((Xbim.Ifc4.MeasureResource.IfcContextDependentMeasure)(object)member), 
			"IfcCountMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcCountMeasure((Xbim.Ifc4.MeasureResource.IfcCountMeasure)(object)member), 
			"IfcDescriptiveMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcDescriptiveMeasure((Xbim.Ifc4.MeasureResource.IfcDescriptiveMeasure)(object)member), 
			"IfcElectricCurrentMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcElectricCurrentMeasure((Xbim.Ifc4.MeasureResource.IfcElectricCurrentMeasure)(object)member), 
			"IfcLengthMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLengthMeasure((Xbim.Ifc4.MeasureResource.IfcLengthMeasure)(object)member), 
			"IfcLuminousIntensityMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcLuminousIntensityMeasure((Xbim.Ifc4.MeasureResource.IfcLuminousIntensityMeasure)(object)member), 
			"IfcMassMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcMassMeasure((Xbim.Ifc4.MeasureResource.IfcMassMeasure)(object)member), 
			"IfcNonNegativeLengthMeasure" => null, 
			"IfcNormalisedRatioMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcNormalisedRatioMeasure((Xbim.Ifc4.MeasureResource.IfcNormalisedRatioMeasure)(object)member), 
			"IfcNumericMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcNumericMeasure((Xbim.Ifc4.MeasureResource.IfcNumericMeasure)(object)member), 
			"IfcParameterValue" => new Xbim.Ifc2x3.MeasureResource.IfcParameterValue((Xbim.Ifc4.MeasureResource.IfcParameterValue)(object)member), 
			"IfcPlaneAngleMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPlaneAngleMeasure((Xbim.Ifc4.MeasureResource.IfcPlaneAngleMeasure)(object)member), 
			"IfcPositiveLengthMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPositiveLengthMeasure((Xbim.Ifc4.MeasureResource.IfcPositiveLengthMeasure)(object)member), 
			"IfcPositivePlaneAngleMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPositivePlaneAngleMeasure((Xbim.Ifc4.MeasureResource.IfcPositivePlaneAngleMeasure)(object)member), 
			"IfcPositiveRatioMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcPositiveRatioMeasure((Xbim.Ifc4.MeasureResource.IfcPositiveRatioMeasure)(object)member), 
			"IfcRatioMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcRatioMeasure((Xbim.Ifc4.MeasureResource.IfcRatioMeasure)(object)member), 
			"IfcSolidAngleMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcSolidAngleMeasure((Xbim.Ifc4.MeasureResource.IfcSolidAngleMeasure)(object)member), 
			"IfcThermodynamicTemperatureMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcThermodynamicTemperatureMeasure((Xbim.Ifc4.MeasureResource.IfcThermodynamicTemperatureMeasure)(object)member), 
			"IfcTimeMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcTimeMeasure((Xbim.Ifc4.MeasureResource.IfcTimeMeasure)(object)member), 
			"IfcVolumeMeasure" => new Xbim.Ifc2x3.MeasureResource.IfcVolumeMeasure((Xbim.Ifc4.MeasureResource.IfcVolumeMeasure)(object)member), 
			"IfcBoolean" => new Xbim.Ifc2x3.MeasureResource.IfcBoolean((Xbim.Ifc4.MeasureResource.IfcBoolean)(object)member), 
			"IfcDate" => null, 
			"IfcDateTime" => null, 
			"IfcDuration" => null, 
			"IfcIdentifier" => new Xbim.Ifc2x3.MeasureResource.IfcIdentifier((Xbim.Ifc4.MeasureResource.IfcIdentifier)(object)member), 
			"IfcInteger" => new Xbim.Ifc2x3.MeasureResource.IfcInteger((Xbim.Ifc4.MeasureResource.IfcInteger)(object)member), 
			"IfcLabel" => new Xbim.Ifc2x3.MeasureResource.IfcLabel((Xbim.Ifc4.MeasureResource.IfcLabel)(object)member), 
			"IfcLogical" => new Xbim.Ifc2x3.MeasureResource.IfcLogical((Xbim.Ifc4.MeasureResource.IfcLogical)(object)member), 
			"IfcPositiveInteger" => null, 
			"IfcReal" => new Xbim.Ifc2x3.MeasureResource.IfcReal((Xbim.Ifc4.MeasureResource.IfcReal)(object)member), 
			"IfcText" => new Xbim.Ifc2x3.MeasureResource.IfcText((Xbim.Ifc4.MeasureResource.IfcText)(object)member), 
			"IfcTime" => null, 
			"IfcTimeStamp" => new Xbim.Ifc2x3.MeasureResource.IfcTimeStamp((Xbim.Ifc4.DateTimeResource.IfcTimeStamp)(object)member), 
			_ => throw new NotSupportedException(), 
		};
	}
}
