namespace Xbim.Ifc4x3.HvacDomain;

public enum IfcCondenserTypeEnum : byte
{
	AIRCOOLED,
	EVAPORATIVECOOLED,
	WATERCOOLED,
	WATERCOOLEDBRAZEDPLATE,
	WATERCOOLEDSHELLCOIL,
	WATERCOOLEDSHELLTUBE,
	WATERCOOLEDTUBEINTUBE,
	USERDEFINED,
	NOTDEFINED
}
