namespace Xbim.Ifc4x3.HvacDomain;

public enum IfcEvaporatorTypeEnum : byte
{
	DIRECTEXPANSION,
	DIRECTEXPANSIONBRAZEDPLATE,
	DIRECTEXPANSIONSHELLANDTUBE,
	DIRECTEXPANSIONTUBEINTUBE,
	FLOODEDSHELLANDTUBE,
	SHELLANDCOIL,
	USERDEFINED,
	NOTDEFINED
}
