<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>buControls</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="buControls.buControlLabel.ico" />
    <EmbeddedResource Include="buControls.buControlLabel.ico" LogicalName="buControls.buControlLabel.ico" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Xml" />
    <Reference Include="System.Data" />
    <Reference Include="buClass">
      <HintPath>..\..\buClass.dll</HintPath>
    </Reference>
    <Reference Include="buCore">
      <HintPath>..\..\buCore.dll</HintPath>
    </Reference>
    <Reference Include="System.Security" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Management" />
  </ItemGroup>
</Project>