namespace Xbim.Ifc2x3.ActorResource;

public enum IfcRoleEnum : byte
{
	SUPPLIER,
	MANUFACTURER,
	CONTRACTOR,
	SUBCONTRACTOR,
	ARCHITECT,
	STRUCTURALENGINEER,
	COSTENGINEER,
	CLIENT,
	BUILDINGOWNER,
	BUILDINGOPERATOR,
	MECHANICALENGINEER,
	ELECTRICALENGINEER,
	PROJECTMANAGER,
	FACILITIESMANAGER,
	CIVILENGINEER,
	COMISSIONINGENGINEER,
	ENGINEER,
	OWNER,
	CONSULTANT,
	CONSTRUCTIONMANAGER,
	FIELDCONSTRUCTIONMANAGER,
	RESELLER,
	USERDEFINED
}
