namespace Xbim.Ifc4x3.ArchitectureDomain;

public enum IfcWindowPanelOperationEnum : byte
{
	BOTTOMHUNG,
	FIXEDCASEMENT,
	OTHEROPERATION,
	PIVOTHORIZONTAL,
	PIVOTVERTICAL,
	REMOVABLECASEMENT,
	SIDEHUNGLEFTHAND,
	SIDEHUNGRIGHTHAND,
	SLIDINGHORIZONTAL,
	SLIDINGVERTICAL,
	TILTANDTURNLEFTHAND,
	TILTANDTURNRIGHTHAND,
	TOPHUNG,
	NOTDEFINED
}
