<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>buMarble</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="-3f0332ae-d170-4f3a-8f28-da14678ac66e-" />
    <None Remove="-73cfefc9-f5c0-4c53-95a2-e57484d2faf2-" />
    <EmbeddedResource Include="-3f0332ae-d170-4f3a-8f28-da14678ac66e-" LogicalName="{3f0332ae-d170-4f3a-8f28-da14678ac66e}" />
    <EmbeddedResource Include="-73cfefc9-f5c0-4c53-95a2-e57484d2faf2-" LogicalName="{73cfefc9-f5c0-4c53-95a2-e57484d2faf2}" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="buEyeBase">
      <HintPath>..\..\buEyeBase.dll</HintPath>
    </Reference>
    <Reference Include="buMotion">
      <HintPath>..\..\buMotion.dll</HintPath>
    </Reference>
    <Reference Include="buControls">
      <HintPath>..\..\buControls.dll</HintPath>
    </Reference>
    <Reference Include="devDept.Eyeshot.v2026">
      <HintPath>..\..\devDept.Eyeshot.v2026.dll</HintPath>
    </Reference>
    <Reference Include="buClass">
      <HintPath>..\..\buClass.dll</HintPath>
    </Reference>
    <Reference Include="Basler.Pylon">
      <HintPath>..\..\Basler.Pylon.dll</HintPath>
    </Reference>
    <Reference Include="System.Management" />
    <Reference Include="devDept.Eyeshot.Control.Win.v2026">
      <HintPath>..\..\devDept.Eyeshot.Control.Win.v2026.dll</HintPath>
    </Reference>
    <Reference Include="buOpcUA">
      <HintPath>..\..\buOpcUA.dll</HintPath>
    </Reference>
    <Reference Include="buCadCamRes">
      <HintPath>..\..\buCadCamRes.dll</HintPath>
    </Reference>
    <Reference Include="buComm">
      <HintPath>..\..\buComm.dll</HintPath>
    </Reference>
    <Reference Include="buCore">
      <HintPath>..\..\buCore.dll</HintPath>
    </Reference>
    <Reference Include="buOpcDlls">
      <HintPath>..\..\buOpcDlls.dll</HintPath>
    </Reference>
    <Reference Include="CmdLangAPI">
      <HintPath>..\..\CmdLangAPI.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>