namespace Xbim.Ifc2x3.SharedBldgServiceElements;

public enum IfcThermalLoadSourceEnum : byte
{
	PEOPLE,
	LIGHTING,
	EQUIPMENT,
	VENTILATIONINDOORAIR,
	VENTILATIONOUTSIDEAIR,
	RECIRCULATEDAIR,
	EXHAUSTAIR,
	AIREXCHANGERATE,
	DRYBULBTEMPERATURE,
	RELATIVEHUMIDITY,
	INFILTRATION,
	USERDEFINED,
	NOTDEFINED
}
