<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UglyToad.PdfPig.DocumentLayoutAnalysis</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UglyToad.PdfPig.Core">
      <HintPath>..\..\UglyToad.PdfPig.Core.dll</HintPath>
    </Reference>
    <Reference Include="UglyToad.PdfPig">
      <HintPath>..\..\UglyToad.PdfPig.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>