using System;
using System.Collections.Generic;
using System.Windows.Forms;
using ModuleWorks;
using ModuleWorks.ToolpathParameters;
using buClass;

internal delegate bool _0001(string P_0, string P_1);
internal delegate string _0002(string P_0, string P_1);
internal delegate bool _0003(object P_0);
internal delegate void _0004(string P_0, string P_1, string P_2, string P_3, double P_4, double P_5, bool P_6);
internal delegate string _0005(object P_0);
internal delegate float _0006(object P_0);
internal delegate double _0007(object P_0);
internal delegate decimal _0008(object P_0);
internal delegate int _000E(object P_0);
internal delegate byte _000F(double P_0);
internal delegate char _0010(byte P_0);
internal delegate void _0011(object P_0);
internal delegate DialogResult _0012(string P_0);
internal delegate void _0013(ref List<string> P_0);
internal delegate string _0014(ref List<string> P_0);
internal delegate string _0015(ref string P_0);
internal delegate Delegate _0016(Delegate P_0, Delegate P_1);
internal delegate ToolHolder _0017(double P_0, double P_1, Unit P_2);
internal delegate ToolHolder _0018(List<Point2d<double>> P_0, Unit P_1);
internal delegate ToolArbor _0019(double P_0, double P_1, Unit P_2);
internal delegate ToolArbor _001A(List<Point2d<double>> P_0, Unit P_1);
internal delegate void _001B(string P_0);
internal delegate Type _001C(RuntimeTypeHandle P_0);
internal delegate int _001D(object P_0);
internal delegate object _001E(Type P_0, int P_1);
internal delegate void _001F();
internal delegate ProgressDescriptionObjectId _007F(object P_0);
internal delegate ProgressDescriptionOperationId _0080(object P_0);
internal delegate string _0081(string[] P_0);
internal delegate void _0082(object P_0, CalculationEventArg P_1);
internal delegate Unit _0083(object P_0);
internal delegate MachiningParams _0084(object P_0);
internal delegate void _0086(object P_0, MachiningParams P_1);
internal delegate IEnumerable<Point3d<double>> _0087(object P_0);
internal delegate void _0088(object P_0, IEnumerable<Point3d<double>> P_1);
internal delegate IEnumerable<Curve> _0089(object P_0);
internal delegate void _008A(object P_0, IEnumerable<Curve> P_1);
internal delegate LinkParams _008B(object P_0);
internal delegate TpCalcMethodsParams _008C(object P_0);
internal delegate WireframeBasedTpCalcParams _008D(object P_0);
internal delegate MachiningAreaRoughingParams _008E(object P_0);
internal delegate MachiningAreaRoughingParamsDepthStepMode _008F(object P_0);
internal delegate DrillingBasedTpCalcParams _0090(object P_0);
internal delegate MachiningParamsMachiningAreaMode _0091(object P_0);
internal delegate MachiningParamsMachType _0092(object P_0);
internal delegate WireframeBasedTpCalcParamsCuttingSide _0093(object P_0);
internal delegate void _0094(object P_0, double P_1);
internal delegate void _0095(object P_0, bool P_1);
internal delegate double _0096(double P_0);
internal delegate void _0097(object P_0, int P_1);
internal delegate void _0098(object P_0, MachiningAreaRoughingParamsDepthStepMode P_1);
internal delegate MachiningAreaHeightsParams _0099(object P_0);
internal delegate TriangleMeshBasedTpCalcParams _009A(object P_0);
internal delegate void _009B(object P_0, MachiningAreaHeightsParamsHeightsType P_1);
internal delegate void _009C(object P_0, MachiningParamsMachType P_1);
internal delegate void _009D(object P_0, MachiningParamsMachiningAreaMode P_1);
internal delegate void _009E(object P_0, WireframeBasedTpCalcParamsCuttingSide P_1);
internal delegate FirstEntry _009F(object P_0);
