using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.ServiceModel;
using System.ServiceModel.Channels;

[assembly: AssemblyDefaultAlias("System.ServiceModel.Http")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.ServiceModel.Http")]
[assembly: AssemblyFileVersion("4.1000.22.41602")]
[assembly: AssemblyInformationalVersion("3.4.0")]
[assembly: AssemblyProduct("Microsoft® .NET Core")]
[assembly: AssemblyTitle("System.ServiceModel.Http")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/wcf")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("4.10.0.0")]
[assembly: TypeForwardedTo(typeof(BasicHttpBinding))]
[assembly: TypeForwardedTo(typeof(BasicHttpMessageCredentialType))]
[assembly: TypeForwardedTo(typeof(BasicHttpMessageSecurity))]
[assembly: TypeForwardedTo(typeof(BasicHttpsBinding))]
[assembly: TypeForwardedTo(typeof(BasicHttpSecurity))]
[assembly: TypeForwardedTo(typeof(BasicHttpSecurityMode))]
[assembly: TypeForwardedTo(typeof(BasicHttpsSecurity))]
[assembly: TypeForwardedTo(typeof(BasicHttpsSecurityMode))]
[assembly: TypeForwardedTo(typeof(HttpRequestMessageProperty))]
[assembly: TypeForwardedTo(typeof(HttpResponseMessageProperty))]
[assembly: TypeForwardedTo(typeof(HttpsTransportBindingElement))]
[assembly: TypeForwardedTo(typeof(HttpTransportBindingElement))]
[assembly: TypeForwardedTo(typeof(IHttpCookieContainerManager))]
[assembly: TypeForwardedTo(typeof(WebSocketTransportSettings))]
[assembly: TypeForwardedTo(typeof(WebSocketTransportUsage))]
[assembly: TypeForwardedTo(typeof(HttpBindingBase))]
[assembly: TypeForwardedTo(typeof(HttpClientCredentialType))]
[assembly: TypeForwardedTo(typeof(HttpProxyCredentialType))]
[assembly: TypeForwardedTo(typeof(HttpTransportSecurity))]
[assembly: TypeForwardedTo(typeof(MessageSecurityOverHttp))]
[assembly: TypeForwardedTo(typeof(NetHttpBinding))]
[assembly: TypeForwardedTo(typeof(NetHttpMessageEncoding))]
[assembly: TypeForwardedTo(typeof(NetHttpsBinding))]
[assembly: TypeForwardedTo(typeof(NonDualMessageSecurityOverHttp))]
[assembly: TypeForwardedTo(typeof(WS2007HttpBinding))]
[assembly: TypeForwardedTo(typeof(WSHttpBinding))]
[assembly: TypeForwardedTo(typeof(WSHttpBindingBase))]
[assembly: TypeForwardedTo(typeof(WSHttpSecurity))]
[assembly: TypeForwardedTo(typeof(WSMessageEncoding))]
