namespace Xbim.Ifc4x3.BuildingControlsDomain;

public enum IfcActuatorTypeEnum : byte
{
	ELECTRICACTUATOR,
	HANDOPERATEDACTUATOR,
	HYDRAULICACTUATOR,
	PNEUMATICACTUATOR,
	THERMOSTATICACTUATOR,
	USERDEFINED,
	NOTDEFINED
}
