namespace Xbim.Ifc4x3.BuildingControlsDomain;

public enum IfcFlowInstrumentTypeEnum : byte
{
	AMMETER,
	COMBINED,
	FREQUENCYMETER,
	PHASEANGLEMETER,
	POWERFACTORMETER,
	PRESSUREGAUGE,
	THERMOMETER,
	VOLTMETER,
	VOLTMETER_PEAK,
	VOLTMETER_RMS,
	USERDEFINED,
	NOTDEFINED
}
